### ISSUE TITLE
AutoValue: generate Comparable.compareTo()

### ISSUE THREAD

**Issue by laec** [google/auto#118]
It will be good for AutoValue to generate the `compareTo` method if the class implements `Comparable`. Because using sorted collections with improperly implemented `Comparable` objects will result in unexpected behavior and hard to track bugs.

From `Comparable`'s Javadoc:
> It is strongly recommended (though not required) that natural orderings be consistent with equals. This is so because sorted sets (and sorted maps) without explicit comparators behave "strangely" when they are used with elements (or keys) whose natural ordering is inconsistent with equals. In particular, such a sorted set (or sorted map) violates the general contract for set (or map), which is defined in terms of the equals method.

> For example, if one adds two keys a and b such that (!a.equals(b) && a.compareTo(b) == 0) to a sorted set that does not use an explicit comparator, the second add operation returns false (and the size of the sorted set does not increase) because a and b are equivalent from the sorted set's perspective.

**Comment by eamonnmcmanus** [comment]
This is explicitly called out [in the documentation](https://github.com/google/auto/tree/master/value#restrictions-and-non-features). We don't generate compareTo because it is not obvious what order the properties should be compared in when there is more than one. Although we could use the same convention as for constructor parameters, we consider the dependency on declaration order to be a weak spot, not something we want to further. The suggestion of using [ComparisonChain](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ComparisonChain.html) still seems the best.
