### ISSUE TITLE
BasicAnnotationProcessor: `instanceof` should not be used

### ISSUE THREAD

**Issue by AriaAdibi** [google/auto#1283]
https://github.com/google/auto/blob/973dcbbd2400ddd9027e43c3d8511f7c96e34006/common/src/main/java/com/google/auto/common/BasicAnnotationProcessor.java#L354

I believe I have spotted an error and wanted to report it. Based on [Element](https://docs.oracle.com/javase/8/docs/api/javax/lang/model/element/Element.html) documentation, `instanceof` should not be used in the aforementioned line. Instead either _visitor_ or `getKind()` should be utilized. Correct me if I am wrong.

Thank you.

**Comment by eamonnmcmanus** [comment]
I think you are right. Well spotted!

**Comment by JakeWharton** [comment]
The Java documentation says that `instanceof` should not be used "for determining the effective class" of an element, but it is still safe for doing an "is-a"-style check. Consider if the backing element class under test implemented both `ExecutableElement` and, say, `TypeElement`. Does this change anything or break the existing code in any way? No, because all we're doing is determining additional capabilities of the element and not attempting to determine its canonical kind.

**Comment by tbroyer** [comment]
The way I understand it, an implementation could have a single concrete type implementing all subinterfaces of `Element` (with specific methods throwing `UnsupportedOperationException` or similar when called on a "wrong" element kind), so the `asExecutable(element)` on the next line might very well throw an `IllegalArgumentException` despite `instanceof ExecutableElement`.

**Comment by JakeWharton** [comment]
Hmm I suppose I can get that from re-reading it a few times.

**Comment by AriaAdibi** [comment]
https://github.com/google/auto/blob/6303fd1cdf5f143a3983594973f0efda049544be/common/src/main/java/com/google/auto/common/MoreTypes.java#L317
