### ISSUE TITLE
AutoValue: Generics error

### ISSUE THREAD

**Issue by kenzierocks** [google/auto#166]
If I make an `@AutoValue` class that extends something like `Iterable`, the generated class will use `<T>` rather than the generic used in the annotated class.

**Comment by kenzierocks** [comment]
Any progress on this?

**Comment by PierreBtz** [comment]
Hello,
Do you have any news on this issue?

Thanks

**Comment by eamonnmcmanus** [comment]
Nothing to report, sorry. It's on my to-do list, but so are a lot of other things.

**Comment by eamonnmcmanus** [comment]
I felt bad about leaving this unaddressed, so I do have a fix in the works. It turns out that Elements.getAllMembers doesn't help, because at least with javac it doesn't do the necessary type substitution for inherited methods. And Types.asMemberOf unfortunately runs into an [Eclipse bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=382590). The Eclipse compiler throws IllegalArgumentException when you ask about Types.asMemberOf with a method inherited from an interface. However, by catching that exception and just not doing the substitution, we can at least have something that works everywhere for methods inherited from classes, and that works everywhere except Eclipse for methods inherited from interfaces. Meanwhile, the Eclipse bug may be fixed in the next release.

**Comment by PierreBtz** [comment]
Many thanks for this quick answer!!

**Comment by elucash** [comment]
2cents: we managed to get it work in [Immutables](/immutables/immutables), essentially, using the combination of `Elements.getAllMembers` for Eclipse and `Types.asMemberOf` for Javac.

**Comment by ltearno** [comment]
I also had to use this kind of tricks when developping hexa.binding
library...

I got on touch with the Immutables team, i think with you Eugène...

Thanks

Arnaud Tournier

**Comment by eamonnmcmanus** [comment]
Thanks for the tip, @elucash! I had put together a fix that worked for methods inherited from superclasses, but not from superinterfaces because of the aforementioned Eclipse bug. But you are right: unlike javac, Eclipse does type substitution in the method return types from `Elements.getAllMembers`, so it's possible to use that as a backup when `Types.asMemberOf` fails. I've made a second fix along those lines and it appears to work for both superclasses and superinterfaces.

On the question of using `getAllMembers` in `findLocalAndInheritedMethods`, the spec guarantees that `TypeElement.getEnclosedElements` will return elements in declaration order, but there is no such guarantee for `Elements.getAllMembers`. This is important for AutoValue since the order of constructor parameters is the order in which the corresponding methods were declared.

**Comment by elucash** [comment]
Yep, it is extra mile to go. If not mention the Eclipse hack to get things in source order (fixed in recent ECJ version), we collect all the elements recursively in predictable linearization order using `TypeElement.getEnclosedElement` with respect to source order, then we match those elements with ones returned by `Elements.getAllMembers` for Eclipse otherwise we do `Types.asMemberOf` for Javac.

**Comment by adrien-aubel** [comment]
I had the same issue when I extended an abstract class with no templated element, but also an interface that had one. The workaround worked though!

In case it may help, when generating the `AutoValue_` classes without the workaround, the unresolved `T` parameter was the first parameter in the generated constructor. With the workaround, it became the last one.
