### ISSUE TITLE
AutoValue_ prefix on class names

### ISSUE THREAD

**Issue by rodolfodpk** [google/auto#172]
I think the AutoValue_ prefix is a bit invasive / annoying. Is there any way to customize the generation of classes names ? For example, instead of class Animal and AutoValue_Animal, I would prefer AbstractAnimal and Animal.

**Comment by eamonnmcmanus** [comment]
We deliberately made it so that the AutoValue_ prefix has to be referenced in exactly one place, which is not visible to clients of the `@AutoValue` class. So its annoyance should be quite limited. If you had AbstractAnimal and Animal then clients would still have to reference AbstractAnimal, which I think would be strange.

Having said that, we are planning to allow some form of pluggability which I expect would make it possible for the `@AutoValue` class Animal to instantiate AnimalImpl rather than AutoValue_Animal. (As presently imagined, AutoValue_Animal would still be generated, but a plugin could additionally generate a subclass of AutoValue_Animal called AnimalImpl, to be referenced from the `@AutoValue` class.)

**Comment by kevinb9n** [comment]
"I think the AutoValue_ prefix is a bit invasive / annoying."

FWIW, that is intentional. It clearly distinguishes it as a code-generated
class, outside the realm of human naming, and it will never conflict with
anything, and it discourages users from referencing the class directly any
more than the one time you have to.

But really: why be bothered by an implementation detail you should so
rarely have to see?

**Comment by rodolfodpk** [comment]
Guys, I realized you are right: it makes sense.
In order to avoid coupling my code with AutoValue_Animal, I just need to use static factories like: 
    static Animal create(String name, int numberOfLegs) {
         return new AutoValue_Animal(name, numberOfLegs);
    }
thanks

**Comment by rodolfodpk** [comment]
and since I need to configure / customize my Gson instance, I also need to put my Gson factory class within the same package of AutoValue_Animal class

**Comment by JakeWharton** [comment]
You can register an instance creator that delegates to the static factory. Or, if you don't mind the occasional `Class.forName` and blindly (de)serializing the AutoValue implementation details, use this: https://gist.github.com/JakeWharton/0d67d01badcee0ae7bc9

**Comment by rodolfodpk** [comment]
Thanks for sharing. I'm using RuntimeTypeAdapterFactory since I have to handle polymorphism but for the other simpler classes now I'm using that AutoGson annotation.
