### ISSUE TITLE
auto-value snapshot versioning

### ISSUE THREAD

**Issue by stevecstian** [google/auto#179]
Should we have snapshot version like `1.1-SNAPSHOT` instead of `1.0-SNAPSHOT` as we have released [auto-value-1.0](https://github.com/google/auto/releases/tag/auto-value-1.0)?

**Comment by stevecstian** [comment]
@eamonnmcmanus Any thoughts?

**Comment by eamonnmcmanus** [comment]
Yes, thanks for pointing this out! @cgruber or I will fix this shortly.

**Comment by stevecstian** [comment]
@eamonnmcmanus :metal:

**Comment by jdaggett** [comment]
@eamonnmcmanus @cgruber Would it be possible to address this issue sometime this week?  As of last Friday, I have preliminary `Builder` support in [jclouds-labs-openstack](https://github.com/jclouds/jclouds-labs-openstack/pull/178). :+1: Unfortunately, the build failed because the `1.0-SNAPSHOT` could not be resolved. Bummer. Is there a way we can get `1.1-SNAPSHOT` builds pushed to the [Sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/google/auto/value/) repo? TIA!

**Comment by cgruber** [comment]
I'm happy to fix this pronto - I'm just weirdly confuse as to why
1.0-SNAPSHOT couldn't be resolved.  I thought sonatype kept the last N
snapshots.  :/

**Comment by jdaggett** [comment]
@cgruber Thank you! Do you have a timeframe for releasing the builder support? Is there any chance of it happening in the next couple of weeks? :smiley:

**Comment by zack-shoylev** [comment]
I just wanted to ask about
https://oss.sonatype.org/content/repositories/snapshots/com/google/auto/value/

Is it supposed to be empty?

**Comment by eamonnmcmanus** [comment]
@zack-shoylev we are investigating.

**Comment by zack-shoylev** [comment]
It seems to be fixed now
https://oss.sonatype.org/content/repositories/snapshots/com/google/auto/value/auto-value/

Thanks!
