### ISSUE TITLE
README.md describes Builder feature which is not included in 1.0 release

### ISSUE THREAD

**Issue by apolatynski** [google/auto#190]
Maybe it would be good to mention in README.md that the Builder feature is not yet released (needs compilation from master)

**Comment by cgruber** [comment]
I have published a snapshot which has these features, and we're putting in place an auto-snapshot travis trigger.

**Comment by rschnitz** [comment]
It seems like the inner Builder interface would be boilerplate - is there a way to simply make it a @Buildable annotation on the basic abstract class?

**Comment by JakeWharton** [comment]
Not without leaking the use of auto value as an implementation detail to all consumers (and thus requiring the general class be public).

**Comment by eamonnmcmanus** [comment]
We should probably have some sort of FAQ for the project. It's a deliberate design decision that the user must write the builder interface. This means that clients can immediately see what the API is without having to know anything about what AutoValue generates. It also means that, as we add features to builders, we will only need to generate exactly what is called for in the user-written interface, rather than every possible method a client might want to use.

**Comment by eamonnmcmanus** [comment]
This is obsolete; the builder feature is included in the released version.
