### ISSUE TITLE
Instantiating classes with null parameter throws IllegalStateException

### ISSUE THREAD

**Issue by rodolfodpk** [google/auto#211]
I have some code using Preconditions.checkNotNull and after migrating it to AutoValue, now I get IllegalStateException instead of NullPointerException. I'm changing my tests but just in case, I believe the correct behavior should be throwing NullPointerException.

**Comment by rodolfodpk** [comment]
Oh, it was my mistake. Actually it's working well.

**Comment by rodolfodpk** [comment]
Inspecting the generated code, I found this line on buid() method: 
 if (!missing.isEmpty()) {
        throw new IllegalStateException("Missing required properties:" + missing);
 }
 So this occurs only when using a Builder.

**Comment by eamonnmcmanus** [comment]
So, to be clear, the issue is that if you have something like this...

```java
@AutoValue
class Foo {
  abstract String bar();
  static Builder builder() {
    return new AutoValue_Foo.Builder();
  }
  @AutoValue.Builder
  interface Builder {
    Builder bar(String x);
    Foo build();
  }
}
```

...then you can write `Foo.builder().bar(null).build()` and instead of throwing NullPointerException for the `bar(null)` it will throw IllegalStateException for the `build()`. That does seem suboptimal and it should be easy enough to fix.

**Comment by eamonnmcmanus** [comment]
This does now throw NullPointerException at the point where the setter is called with a null argument.
