### ISSUE TITLE
AutoValue should reject `@Nullable` on primitive properties

### ISSUE THREAD

**Issue by esnellman** [google/auto#254]
Hi all,

If I have a primitive type field and i annotate it with @Nullable.  The Builder it-self will use an Object type instead.  However when .build() is called it will pass the field into the method constructor method invocation.  This forces auto-unboxing and NPE if null.  Can we code this to instead do a null check and pass in default primitive values?  Or can we have the builder use primitives and use a internal mask(s) state machine to verify the null contact?

Thank You!!

**Comment by lowasser** [comment]
Wait, what?  What would you expect a @Nullable primitive to do?  That
sounds nonsensical.

**Comment by esnellman** [comment]
```Java
@AutoValue
public abstract class Nonsensical {
  @Nullable
  public abstract long field1();

  public abstract long field2();

  public static Builder builder() {
    return new AutoValue_Nonsensical.Builder();
  }

  public abstract Builder toBuilder();

  @AutoValue.Builder
  public interface Builder {
    Builder field1(long v);

    Builder field2(long v);

    Nonsensical build();
  }
}
```
Produces this builder



```Java
  static final class Builder implements Nonsensical.Builder {
    private Long field1;
    private Long field2;
    Builder() {
    }
    Builder(Nonsensical source) {
      this.field1 = source.field1();
      this.field2 = source.field2();
    }
    @Override
    public Nonsensical.Builder field1(long field1) {
      this.field1 = field1;
      return this;
    }
    @Override
    public Nonsensical.Builder field2(long field2) {
      this.field2 = field2;
      return this;
    }
    @Override
    public Nonsensical build() {
      String missing = "";
      if (field2 == null) {
        missing += " field2";
      }
      if (!missing.isEmpty()) {
        throw new IllegalStateException("Missing required properties:" + missing);
      }
      return new AutoValue_Nonsensical(
          this.field1,
          this.field2);
    }
  }
```

**Comment by eamonnmcmanus** [comment]
I suppose AutoValue should produce an error if you apply `@Nullable` to a property of primitive type. Obviously `field1()` can never return null in the example.

**Comment by esnellman** [comment]
I would rather the builder it self just uses primitive types and not track
if a field has been set or not.

**Comment by eamonnmcmanus** [comment]
Well, that's a different issue. We made the design decision to require primitive and non-`@Nullable` reference properties to be given an explicit value, possibly before the builder is returned from the `static Builder builder()` method. I think we're unlikely to change that.

It happens to mean that we can track whether properties have been set by using null, but that's an implementation detail. (An earlier version did use a BitSet to track this, but we changed it because GWT doesn't support BitSet.)

**Comment by esnellman** [comment]
I wish GWT was not holding back..  Anyway to add a annotation to bring back
BitSet / primitive builders?

Well then for @Nullable primitive fields do a ternary null check in the
constructor invocation, if null pass in a default value else unbox.

**Comment by eamonnmcmanus** [comment]
I'm not convinced that would be a good idea. It seems at least as likely that users would want a NullPointerException as that they would want a default value of 0, if they pass a null Integer to an int property. Just like when you assign an Integer to an int.

**Comment by esnellman** [comment]
No user is expecting a NPE from unboxing especially since they annotated
nullable and already pass the illegal argument exception checks

**Comment by eamonnmcmanus** [comment]
I don't follow that. We should not allow users to annotate primitive properties with `@Nullable` because that makes no sense.
```java
@AutoValue
abstract class Foo {
  @Nullable abstract int bar();  // what??
}
```

So you must write something like this:
```java
@AutoValue
abstract class Foo {
  abstract int bar();
  static Builder builder() {
    return new AutoValue_Foo.Builder();
  }
  interface Builder {
    Builder setBar(int x);
    Foo build();
  }
}
```

Then if you call `Foo.builder().setBar((Integer) null).build()` you will get a NullPointerException, which is completely consistent with what happens anywhere else in the language.

**Comment by esnellman** [comment]
The NPE in your example above ```Foo.builder().setBar((Integer) null).build()``` is thrown outside of the interface boundary and thus not inside AutoValue.  Also this hits on obvious Java language knowledge that most users should be aware of.

The NPE I am reporting is from un-boxing a null that occurs inside the generated .build() code in a generate builder:
```Java
new AutoValue_Nonsensical(
          this.field1,//NPE here!
```

Going forward, you have offered the solution to instead ignore ```@Nullable``` for primitive types and thus we will see a ```IllegalStateException``` instead of NPE.  
To me in its current form this violates the principle of least astonishment.  A new user viewing the wiki today has no idea that the builder uses objects especially since the method and field signatures on the wiki have primitives.  Consider adding some clarifications to the wiki and explain the design decisions taken where a Builder uses objects types instead of primitives.  I hope you do change your mind on primitives.

My workaround will be that each time I add a new optional field I will have add a setter for that field in ```public static Builder builder()``` 

Please document this on the wiki.

Please consider adding an additional builder ```@AutoValue.PrimitiveBuilder``` where primitives are allowed and primitives are not checked.

**Comment by eamonnmcmanus** [comment]
I think I see the source of the confusion. AutoValue really uses `@Nullable` to mean two different things. One is the literal meaning, that the property in question can be null. That obviously doesn't apply to primitive properties. The second is an additional meaning with builders, that the property can be omitted from the builder, and will default to null. You would like this meaning to be extended to primitive types, with the meaning of defaulting to the default value for the type. I don't really think that's feasible as such, since we can't really ask people to write a nonsensical `abstract @Nullable int foo()` to mean that `foo` is optional. And in fact when I said above that AutoValue should produce an error for this, I meant a compile-time error.

We could imagine an explicit `@Default` annotation or the like, so you could write `abstract @Default int foo()` and perhaps even `abstract @Default("23") int foo()`. However I'm not sure that such a feature would really pull its weight, beyond what can already be done just by adding a setter call with the default in `public static Builder builder()`.

I will anyway take a look at the documentation and see if this can be made clearer as you suggest.

**Comment by eamonnmcmanus** [comment]
I am planning to make it an error for a primitive property to be `@Nullable`.

**Comment by jarettmillard** [comment]
@eamonnmcmanus Is there a possibility that an `@Default` annotation will ever be added? I realize that builders are the chosen way to set default values, but API model (de)serialization is a huge use case for AutoValue extensions. For objects that are only consumed and never instantiated directly, writing a builder just to set optional fields makes for a lot of repetition to do something that should be simple.

**Comment by eamonnmcmanus** [comment]
@jarettmillard could you give a short example of the sort of thing you are talking about, and how `@Default` might address it?

**Comment by jarettmillard** [comment]
I submitted a [pull request](https://github.com/rharter/auto-value-moshi/pull/19) to auto-value-moshi for a similar feature, but it was rejected with a few good reasons. If there was official support for `@Default` those reasons shouldn't apply anymore. In the case of multiple extensions that all need default values, having one official way to indicate them seems to me like it would work out better than the proposed default builder solution.

**Comment by eamonnmcmanus** [comment]
I'm afraid I'll have to ask you to spell out your use case for me. Deciphering it from your PR is a lot to ask of me and of other people looking at this issue. Could you give an example of what you would like users to be able to write in an `@AutoValue` class and how it would affect the generated code? Would this be something that only extensions would use or that the base builder support would also include?

I'm going to close this issue because AutoValue does now reject `@Nullable` on primitive properties. I suggest opening a new issue to cover the `@Default` proposal.
