### ISSUE TITLE
AutoValue builders (+ constructors?) with more permissive generics

### ISSUE THREAD

**Issue by kenzierocks** [google/auto#256]
Currently builders and constructors only take in the precise generic that matches the return type, if I put `List<String>` I must give a `List<String>`. However, it's generally a good idea to have the methods that accept lists and other collections take `List<? extends String>`. This requires strange naming in the builder when hiding the abstract methods and providing others due to erasue:

``` java
@AutoValue
public abstract class Foo {
  @AutoValue.Builder
  public abstract class Builder {
    // what do I call this?
    public final Builder list2(List<? extends String> list) {
      return list((List<String>) list);
    }

    abstract Builder list(List<String> list);

    public abstract Foo build();
  }

  public abstract List<String> list();

}
```

I could make `list` here return `List<? extends String>`, but then using the return value is problematic.

Here's an example: [gist](https://gist.github.com/kenzierocks/04341ce6e802143a6383). It's a bit contrived, but that's the general idea. I'm hoping there's a decent fix that someone can suggest, but for now I'll just be renaming methods.

**Comment by sherter** [comment]
> However, it's generally a good idea to have the methods that accept lists and other collections take List<? extends String>.

That's not necessarily a good idea. In fact it's a very bad idea if you want to add more elements to the collection (read [Effective Java, Item 28](https://books.google.de/books?id=ka2VUBqHiWkC&pg=PA134#v=onepage&q&f=false)).

Your cast in `list2()` is not safe! If you really need the flexibility, you have to do something like this:

```java
public final Builder list2(List<? extends String> list) {
  List<String> copy = new ArrayList<>();
  copy.addAll(list);
  return list(copy);
}
```

That's not something the library can (or should) do for you, because we cannot know which list type is appropriate for your use case.

**Comment by kenzierocks** [comment]
I think I didn't get my point across correctly. I want the library to accept the `super`/`extends` versions as valid versions of the property, in addition to supporting the immediate generic.

**Comment by eamonnmcmanus** [comment]
Since AutoValue classes are supposed to be immutable, AutoValue properties that are collections should be immutable collections. So we have some special treatment for Guava's immutable types such as [ImmutableList](http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/com/google/common/collect/ImmutableList.html). In particular, if you have a property of type `ImmutableList<Foo>` then its builder can indeed have a setter that takes `ImmutableList<? extends Foo>`. The generated builder will copy the argument value using [`ImmutableList.copyOf`](http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/com/google/common/collect/ImmutableList.html#copyOf(java.lang.Iterable)), which does nothing in this case since the argument is already an `ImmutableList`.

We could extend this treatment to arbitrary `List` etc, using code similar to what @sherter wrote above, but then in cases like this we would need to decide that the new `List` is an `ArrayList` rather than any other implementation of `List`, etc, and that is much less obviously the right thing to do.

@kenzierocks touches on another concern, though, which is that sometimes you would like a setter method in the public API to be able to call the generated setter method for the same property, like `list2` calling `list` in the example. There _is_ currently a way to achieve this, but it is ugly. Builders can use methods that look like either `setFoo(int x)` or `foo(int x)`, as long as all the abstract setter methods follow the same one of these two conventions. So you can have package-private abstract setter methods following the convention you _don't_ want in your public API, and public concrete setter methods that call those. The example would have looked something like this in that case:
```java
@AutoValue
public abstract class Foo {
  @AutoValue.Builder
  public abstract static class Builder {
    public final Builder list(List<? extends String> list) {
      return setList((List<String>) list);
    }
    abstract Builder setList(List<String> list);
    public abstract Foo build();
  }
  public abstract List<String> list();
}
```
Of course you then need to define both `bar` and `setBar` for every property, even the ones where `bar` just calls `setBar`. We don't really think this is a satisfactory solution, but we're not sure either what a better solution should look like or whether it is worth complicating the spec still further to allow it.

**Comment by kenzierocks** [comment]
The ImmutableList may cover my use case, I didn't realize it would work with that.
