### ISSUE TITLE
Could autovalue not work with interface?

### ISSUE THREAD

**Issue by jmfayard** [google/auto#269]
Hello, this is just a question, and probably trivial, 
but I am curious about why AutoValue could not work with interface
which after all are static and abstract

Example: 
```
import com.google.auto.value.AutoValue;

class Example {
    @AutoValue
    interface Animal {
        String name();
        int numberOfLegs();
    }
    Animal create(String name, int numberOfLegs) {
        return new AutoValue_Example_Animal(name, numberOfLegs);
    }
}
```

**Comment by sherter** [comment]
It would work with interfaces, but it would be less powerful. In interfaces all methods are abstract by default. In abstract classes you _can_ have non-abstract methods (i.e. implementations):

```java
@AutoValue
abstract class Rectangle {
  abstract int width();
  abstract int height();

  int area() { // will be inherited by generated class
    return width() * height();
  }  
```

**Comment by tbroyer** [comment]
@sherter Not true in Java 8.

```java
@AutoValue
interface Rectangle {
  int width();
  int height();

  default int area() { // will be inherited by generated class
    return width() * height();
  }
}
```

**Comment by tbroyer** [comment]
See #86

**Comment by jbgi** [comment]
value type inheritance is considered a bad practice hence interface are (intentionally) not supported, I believe. also the reason why am explicit, single, no-arg package-private, constructor is recommended for annotated abstract class.

**Comment by jmfayard** [comment]
@tbroyer @jbgi thanks, it makes sense.
@sherter for the record, my example does not compile
`Error:(7, 5) error: @com.google.auto.value.AutoValue only applies to classes`

**Comment by kevinb9n** [comment]
Is there any advantage to support interfaces other than letting you omit
"public abstract" from your methods? We haven't thought of it. In
particular, we cannot imagine any decent reason to ever have a second
implementation, or <shudder> to mock a value type.

If we did support interfaces, we'd have to add text to our documentation
begging people to not use the feature we just added. Since the generated
implementation is hidden and only this type is exposed, this is the type
that you need consumers to trust the immutability of.  It's hard to trust
the immutability of an interface.


On Thu, Sep 10, 2015 at 3:48 AM, Jean-Michel Fayard <
notifications@github.com> wrote:

> Hello, this is just a question, and probably trivial,
> but I am curious about why AutoValue could not work with interface
> which after all are static and abstract
>
> Example:
>
> import com.google.auto.value.AutoValue;
>
> class Example {
>     @AutoValue
>     interface Animal {
>         String name();
>         int numberOfLegs();
>     }
>     Animal create(String name, int numberOfLegs) {
>         return new AutoValue_Example_Animal(name, numberOfLegs);
>     }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/auto/issues/269>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by jmfayard** [comment]
@kevinb9n I think I wrote 20 interfaces for each abstract class I wrote, so it's probably just a familiarity bias.

**Comment by josephjang** [comment]
FYI, the following SonarQube rule made me curious about this issue:
https://sonarqube.com/coding_rules#rule_key=squid%3AS1610

**Comment by jbgi** [comment]
@josephjang If `equals`/`hashCode`/`toString` did not exist/where not generated by autovalue it would be much less problematic to use interfaces (assuming that all implementations are immutable).

**Comment by eamonnmcmanus** [comment]
The SonarQube rule gives no rationale. There's another reason not mentioned there for using an abstract class rather than an interface: an abstract class can have a package-private constructor, to prevent subclassing outside the package. And (as @jbgi mentioned earlier) we do in fact recommend that with AutoValue.
