### ISSUE TITLE
AutoValue: Support withXyz setters on Builders

### ISSUE THREAD

**Issue by zkiss** [google/auto#276]
It is common practice to prefix property setter methods on builders with `with`. This naming style however is not supported by `AutoValue.Builder`. According to the docs, only no prefix and `set` is supported.

It would be nice if at least the `with` prefix was supported, but maybe the ability to set this to any arbitrary value would not be too bad.

```
@AutoValue
abstract class Foo {

  public static Builder builder() {
    return new AutoValue_Foo.Builder();
  }

  public abstract String getBar();

  @AutoValue.Builder
  public static abstract class Builder {
    public abstract Builder withBar(String bar);
    public abstract Foo build();
  }
}
```

**Comment by eamonnmcmanus** [comment]
We're very conservative about adding any complexity to the specification of AutoValue. I'm not sure I really see a compelling argument here. You always have the option of exporting a public API that is different from the abstract methods that AutoValue expects:

```java
@AutoValue
public abstract class Foo {

  public static Builder builder() {
    return new AutoValue_Foo.Builder();
  }

  public abstract String getBar();

  @AutoValue.Builder
  public static abstract class Builder {
    public Builder withBar(String bar) { setBar(bar); }
    abstract Builder setBar(String bar);  // not public
    public abstract Foo build();
  }
}
```

**Comment by zkiss** [comment]
@eamonnmcmanus In my opinion that solution is "mechanical, repetitive, typically untested and sometimes the source of subtle bugs. *Sounds like a job for robots!*"

My reasons for requesting the feature are:
* with the proposed solution the method naming convention is not enforced by AutoValue's code generator (while set and no-prefixes are)
* Instead of 2, there are 3 things to do manually every time a property changes (add, remove, rename)
* `with` is a widely used prefix in builders, I'd even risk that it's more popular than `set`

**Comment by tbroyer** [comment]
FWIW, I've seen `with` used with immutable objects to rather create a copy with a property having a different value: https://immutables.github.io/immutable.html#copy-methods & https://projectlombok.org/features/experimental/Wither.html
That said, it's possible to configure some generators (e.g. [Immutables](https://immutables.github.io/immutable.html#builder), with `@Style(init="with*")`) to output withers on builders; but AutoValue is and has always been opinionated rather than configurable. Maybe Immutables would be a better fit than AutoValue for what you need/want?

**Comment by zkiss** [comment]
Understood. I thought it was worth the suggestion :)
