### ISSUE TITLE
Constructor parameters generated in incorrect order when using ECJ

### ISSUE THREAD

**Issue by facboy** [google/auto#292]
I think the constructors are not generated correctly when an ancestor class is used in 1.1, together with ECJ 4.4 in Intellij.  In the docs it states that the generated constructor should match the order that the abstract accessors are declared in, but if i have

```java
public abstract class BaseArgs {
    public abstract Object getFoo();
    public abstract Object getBar();
}
```

and 

```java
@AutoValue
public abstract class SameArgs extends BaseArgs {
}

...

@AutoValue
public abstract class MoreArgs extends BaseArgs {
    public abstract Object getMoreFoo();
}
```

The generated constructor I get is

```java
AutoValue_MoreArgs(
      Object bar,
      Object foo,
      Object moreFoo) {
    if (bar == null) {
      throw new NullPointerException("Null bar");
    }
    this.bar = bar;
    if (foo == null) {
      throw new NullPointerException("Null foo");
    }
    this.foo = foo;
    if (moreFoo == null) {
      throw new NullPointerException("Null moreFoo");
    }
    this.moreFoo = moreFoo;
  }
```

which doesn't match what I would expect.  Shouldn't it be `AutoValue_MoreArgs(foo, bar, moreFoo)`?

I think I've seen it randomly change the order of the arguments too (ie there were no changes to `BaseArgs` but the order of `foo` and `bar` in `AutoValue_MoreArgs()` changed when the class was re-generated).

I'm not sure whether having a child that adds no additional accessors (`SameArgs`) is necessary to reproduce, but that is the structure that I was using at the time.

**Comment by eamonnmcmanus** [comment]
I thought I had commented on this issue when it was filed but apparently not! There was a longstanding bug in the Eclipse compiler where it would sort members of a class or interface before presenting them to the annotation processing API. I'm pretty sure that is what you are seeing here. There's [code](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/EclipseHack.java) in AutoValue that attempts to fix the problem, by opening the files itself and scanning them using a very superficial parser, but it looks as if this is not working in your case, probably because that code is expecting to find itself in Eclipse rather than IntelliJ.

The Eclipse bug was fixed in 4.5 so you should be able to upgrade to that and have everything behave as it should. Let me know if that doesn't work.
