### ISSUE TITLE
AutoFactory: Composition of factories broken

### ISSUE THREAD

**Issue by mkaulig** [google/auto#297]
When referencing a auto generated factory in another auto generated factory the reference is not fully qualified and thus can not be resolved. Here is an example:

``` java
package autoFactoryTest.sub;

import com.google.auto.factory.AutoFactory;

@AutoFactory
public class B {
}
```

``` java
package autoFactoryTest;

import com.google.auto.factory.AutoFactory;
import autoFactoryTest.sub.BFactory;

@AutoFactory
public class A {
    public A(BFactory b) {
    }
}
```

The reference to `BFactory` from `AFactory` is not fully qualified which cannot be resolved:

``` java
import javax.annotation.Generated;
import javax.inject.Inject;
@Generated("com.google.auto.factory.processor.AutoFactoryProcessor")
public final class AFactory {
  @Inject
  public AFactory() {
  }
  public A create(BFactory b) {
    return new A(b);
  }
}
```

compilation error:

```
[ERROR] diagnostic: target/generated-sources/apt/autoFactoryTest/AFactory.java:8: error: cannot find symbol
```

**Comment by foxylion** [comment]
Any updates on this? I'm having the same issues.

**Comment by rafagcamargo** [comment]
Facing same issue, any updates?

**Comment by Redwid** [comment]
Got the same issue.
Any way to fix that?

**Comment by foxylion** [comment]
@Redwid A fix is to use the full qualified class name. In the example the constructor of `A` should look like this: `public A(autoFactoryTest.sub.BFactory b) {}`

**Comment by Redwid** [comment]
@foxylion thanks,
Already found that solution in another thread: https://github.com/google/auto/issues/124

**Comment by Double-O-Seven** [comment]
Is there going to be a fix for this any time soon?

**Comment by pthomain** [comment]
Any update on this?

**Comment by eamonnmcmanus** [comment]
The issue in the example is that the `BFactory` class doesn't exist when AutoFactory is processing `A`, but AutoFactory doesn't notice that and generates code anyway. If it had type-deferral logic, similar to the [logic](https://github.com/google/auto/blob/b9ba06a327d08a741ed70f1573540e063fb6c69c/value/src/main/java/com/google/auto/value/processor/AutoValueOrOneOfProcessor.java#L292) already present in AutoValue, then it could defer processing `A` to a later annotation processing round. At that point, `B` will have been processed (it doesn't reference any undefined types), so `BFactory` will have been generated.

It might even be enough for `AutoFactoryProcessor` to extend [`BasicAnnotationProcessor`](https://github.com/google/auto/blob/master/common/src/main/java/com/google/auto/common/BasicAnnotationProcessor.java).

**Comment by eamonnmcmanus** [comment]
Having looked into this in greater detail, I find that the situation is more complicated than I described.

You can currently have two `@AutoFactory` classes that reference each other mutually, like this:
```
@AutoFactory class Foo {
  Foo(@Provided BarFactory bar) {...}
}

@AutoFactory class Bar {
  Bar(@Provided FooFactory foo) {...}
}
```

When I tried to do the `BasicAnnotationProcessor` thing I described, this failed, because each of `Foo` and `Bar` has a currently-undefined reference so we generate the factories for neither of them. I found cases in Google's code base that look very like this and that would therefore be broken by the proposed change or similar changes.

The reason that this works currently, if `Foo` and `Bar` are in the same package, is that code like [this](https://github.com/google/auto/blob/b9ba06a327d08a741ed70f1573540e063fb6c69c/factory/src/main/java/com/google/auto/factory/processor/FactoryWriter.java#L121) and [this](https://github.com/google/auto/blob/b9ba06a327d08a741ed70f1573540e063fb6c69c/factory/src/main/java/com/google/auto/factory/processor/FactoryWriter.java#L222) does not particularly notice when the `TypeMirror` in question is actually an `ErrorType`. JavaPoet deliberately allows `TypeName.get(t)` to work when `t` is an `ErrorType`. When it's outputting the type in question, it will use whatever string the `ErrorType` said. So in the example, `BarFactory` doesn't exist when `Foo` is being processed, so we get an `ErrorType[BarFactory]`. If we output `FooFactory` and just blindly use that type, that will eventually compile, because what appears in the generated source is the `BarFactory` string from the `ErrorType`, and `BarFactory` will eventually exist after `Bar` is processed. If `BarFactory` is in a different package then this won't work, because the `ErrorType` won't include a package name even if `BarFactory` is imported. But if you explicitly write `some.package.BarFactory` in the parameter declaration, instead of relying on an import, then that is the string that will appear in the `ErrorType` and therefore in the generated code. That's why that workaround functions.

I'm not sure there's really a clean way to make this work for the case in question while continuing to allow it to work for cases like example I wrote above. Possibly, if the processor  sees an `ErrorType` for `BarFactory` and if there is a `Bar` in the `@AutoFactory` classes currently being processed, it could assume that that's where `BarFactory` is going to come from, and it could generate a `TypeName` with the correct package. That assumption is not 100% reliable, however, and would obviously fail if you had more than one `@AutoFactory Bar` in different packages being compiled at the same time.

**Comment by Quantum64** [comment]
It's great to see this resolved!

**Comment by iskuhis** [comment]
@Quantum64 how it is resolved ? 
Currently what I do is in constructor of `@AutoFactory Class A`  I specify the whole path of  `@AutoFactory Class B`, 
but wondering is this is  a solution ? 
```@AutoFactory 
class A (@Provided com.xxx.B b)
```

**Comment by eamonnmcmanus** [comment]
We need to make a release of AutoFactory where this fix is present.

**Comment by pthomain** [comment]
@eamonnmcmanus Great news, thanks for looking into it :)
