### ISSUE TITLE
Provide a better way to tell if a builder property has been set

### ISSUE THREAD

**Issue by hgschmie** [google/auto#300]
One of the nice things in the builders for auto value is being able to preprocess the values in the builder before returning the bean as described in https://github.com/google/auto/tree/master/value#other-preconditions-or-preprocessing. It also states that "Sometimes it may be more convenient to consult the value in the builder before calling autoBuild()."

Consider the following bean which has two fields, userName and displayName. 

```java
@AutoValue
public abstract class Bean1 {
    Bean1() {}

    public abstract String getUserName();
    public abstract String getDisplayName();

    public abstract Builder toBuilder();

    public static Builder builder()
    {
        return new AutoValue_Bean1.Builder();
    }

    @AutoValue.Builder
    public abstract static class Builder {

        public abstract Builder userName(String userName);
        public abstract Builder displayName(String displayName);

        public abstract Bean1 build();
    }
}
```

The use case is that it should be possible to construct it either with supplying both fields or only userName. In the latter case, displayName should have the same value as user name. The bean itself, must never return a null value for either displayName or userName. So, adding the following code to the builder should do the trick:

```java
        abstract String getUserName();
       abstract String getDisplayName();

        abstract Bean1 autoBuild();

        public Bean1 build() {
            if (getDisplayName() == null) {
                displayName(getUserName());
            }

            return autoBuild();
        }
```

However, it does not. Because the getDisplayName() method does not actually allow inspection of the value in the builder but validates it first. From `AutoValue_Bean1.Builder`:

```java
    @Override
    public String getDisplayName() {
      if (displayName == null) {
        throw new IllegalStateException("Property \"displayName\" has not been set");
      }
      return displayName;
    }
```

The only way around this is to add a `@Nullable` annotation to the (user-visible) `getDisplayName()` method in Bean1. So now, every user of Bean1 will check this property for a null return value even though the contract of the bean enforces that the values should never be null (it is even worse, with being required to add the `@Nullable` annotation, the builder now no longer enforces the requirement with the field being non-null in its `autoBuild()` method.

The internal getter methods for the builder should not validate the values in the builder. This should be the prerogative of the `build()` or `autoBuild()` methods. Validating on the getters (and not allowing any access to the internal state of the builder) makes custom bean building and validation actually harder, not easier.

**Comment by hgschmie** [comment]
See https://github.com/hgschmie/autovalue for example code. The examples above are the `VanillaBean`, the only working variant (passing all tests) is the `NullableBean`.

**Comment by hgschmie** [comment]
more than two weeks passed and not a single comment? @eamonnmcmanus @kevinb9n  ?

**Comment by eamonnmcmanus** [comment]
If I understand correctly, the proposal is for `getFoo()` in a builder to return null if the `foo` property has not been set, rather than throwing an exception as at present. But what about primitive properties? Would we want to silently return say `0.0` or `false` for a `double` or `boolean` property that has not been set? That feels strange. I think the right solution is the one proposed in #278, of allowing the getter to return `Optional<T>` as an alternative to `T`; I see @hgschmie has commented there too. We would allow `Optional<Integer>` or `OptionalInt` for a property of type `int`.

There does seem to be demand for this so I'll look into getting it done. Meanwhile, the following workaround is about the best you can do:

```java
  public Bean1 build() {
    try {
      getDisplayName();
    } catch (IllegalStateException e) {
      displayName(getUserName());
    }
    return autoBuild();
  }
```

It's a bit clunky, but it does avoid polluting the user-visible API with a `@Nullable` that is a lie.

**Comment by hgschmie** [comment]
Yes, as you point out in your code example, I want to have access to the "raw" state of the property in the builder without having the getter penalizing me with an IllegalStateException. Having an `Optional<T>` getter for a property of `T` is fine, but it will get a bit awkward because Beans with "normal" attributes and "optional" attributes would (should) look the same in the Builders:

```java
@AutoValue
class Bean1 {
  String getFoo();

  public static Builder builder() { return new AutoValue_Bean1.Builder(); }

  @AutoValue.Builder
  abstract static class Builder {
    abstract Builder foo(String foo);

    abstract Optional<String> getFoo();

    Bean1 build() {
      if (getFoo().isPresent()) {
       ...
      }
     return autoBuild();
  }
}
```

and 

```java
@AutoValue
class Bean1 {
  Optional<String> getFoo();

  public static Builder builder() { return new AutoValue_Bean1.Builder(); }

  @AutoValue.Builder
  abstract static class Builder {
    abstract Builder foo(Optional<String> foo);

    abstract Optional<String> getFoo();

    Bean1 build() {
      if (getFoo().isPresent()) {
       ...
      }
     return autoBuild();
  }
}
```

This use would require to preset `Optional` properties with `Optional.empty()` / `Optional.absent()` values. Otherwise, you end up with this:

```java
@AutoValue
class Bean1 {
  Optional<String> getFoo();

  public static Builder builder() { return new AutoValue_Bean1.Builder(); }

  @AutoValue.Builder
  abstract static class Builder {
    abstract Builder foo(Optional<String> foo);

    abstract Optional<Optional<String>> getFoo();

    Bean1 build() {
      if (getFoo().isPresent()) {
       ...
      }
     return autoBuild();
  }
}
```

I assume that no one wants that. :-)

**Comment by hgschmie** [comment]
I have to admit that simply closing this with "look somewhere else" feels a bit rude to me.

**Comment by eamonnmcmanus** [comment]
Sorry, I think I got confused between the issues that are here on github and the ones we have on our internal issue tracker. There is not in fact an issue here covering how builder property values might be consulted without getting IllegalStateException, and I think this one could reasonably serve that purpose. #278 in fact just proposes to special-case `Optional<T>` so that properties of that type default to `Optional.empty()`. Given that, you would not need to wrap `Optional<Optional<String>>` in the second example, since getFoo() would always return an `Optional` and never throw IllegalStateException. So, I still think this is a better solution than having builder getters always succeed, and inventing default values if necessary.

Since we don't currently special-case `Optional<T>`, properties of that type currently have three possible states: set to `Optional.empty()`, set to `Optional.of(something)`, and never set. That's confusing, and I don't think we want it. We explicitly don't have it for `@Nullable` properties. *But*, for properties of primitive or non-`@Nullable` type, I *do* think we want to distinguish between the two states of *set to something* or *never set*. Using `null` to indicate *never set* is a potential solution; we could handle primitives by allowing the builder getter for an `int` property to return `Integer`, etc, and still throw IllegalStateException for never-set properties if the builder getter returns `int`. But I still think the `Optional` solution is cleaner. Additionally, we already have the IllegalStateException behaviour and removing it has a strong risk of breaking existing code in hard-to-find ways.

My apologies for not looking closely enough earlier.

**Comment by facboy** [comment]
As an alternative, is it possible to allow builders to have 'concrete' implementations of setters or getters for a property?  At the moment if auto-value doesn't find an abstract setX method on the builder then it complains, could it instead just use a concrete getX/setX with the correct signatures?

**Comment by eamonnmcmanus** [comment]
@facboy that's an interesting idea, which I'll have to think about more. Taking the original example (displayName defaults to userName unless it has been set explicitly), if I'm understanding correctly, it would be something like this:

```java
@AutoValue
public abstract class Foo {
  public abstract String userName();
  public abstract String displayName();

  public static Builder builder() {
    return new AutoValue_Foo.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {
    private String displayName;
    public Builder setDisplayName(String displayName) {
      Preconditions.checkNotNull(displayName);
      this.displayName = displayName;
    }
    String displayName() {
      return displayName;  // possibly null
    }

    public abstract Builder setUserName(String userName);
    abstract String userName();

    abstract Foo autoBuild();

    public Foo build() {
      if (displayName == null) {
        displayName = userName();  // exception if userName not set
      }
      return autoBuild();
    }
  }
}    
```

The generated `autoBuild()` method would call `displayName()` instead of using its own private `displayName` field.

Contrast with the `Optional` solution:
```java
@AutoValue
public abstract class Foo {
  public abstract String userName();
  public abstract String displayName();

  public static Builder builder() {
    return new AutoValue_Foo.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {
    public abstract Builder setDisplayName(String displayName);
    abstract Optional<String> displayName();

    public abstract Builder setUserName(String userName);
    abstract String userName();

    abstract Foo autoBuild();

    public Foo build() {
      if (!displayName().isPresent()) {
        setDisplayName(userName());  // exception if userName not set
      }
      return autoBuild();
    }
  }
}    
```

The `Optional` version is shorter, but the custom-setters-and-getters version does have the potential to solve other problems too.

**Comment by hgschmie** [comment]
with the upcoming 1.2 release, any change that this will make it in? Given that this project releases every 6-12 months, I would otherwise have to fork and hack my own version of autovalue.

**Comment by facboy** [comment]
@eamonnmcmanus to be honest, I naively thought that's just how it would work :).  In the 'main' AutoValue'd class you can specify equals/hashCode and then they won't be generated.  I assumed that if I specified a getter/setter in the abstract builder class then the generated class would just use those instead.  So perhaps it fits nicely with the existing behaviour too?

**Comment by eamonnmcmanus** [comment]
Well, it's slightly more complicated, in that there can be two methods (getter and setter) and it's possible that one of them would be concrete and the other abstract. I think what we have is this:

 | abstract getter | concrete getter
-------|-------|------
abstract setter | current behaviour | not allowed (1)
concrete setter | getter overridden (2) | getter called from generated `build()`

If the setter is abstract but the getter is concrete (1) then the setter would put the set value somewhere that the getter can't get it. If the getter is abstract but the setter is concrete (2) then the generated class can override the setter and call `super.setFoo(x)` while also saving the set value for use by the getter and by `build()`. This last case also applies if there is no getter. It's interesting because it also gives you a way to valid properties as they are set: do the validation in a concrete setter, and allow the generated override to take care of saving the value:

```java
@AutoValue
public abstract class Foo {
  public abstract String userName();

  @AutoValue.Builder
  public abstract static class Builder {
    public Builder setUserName(String s) {
      Preconditions.checkArgument(!s.isEmpty());
      return this;
    }
  }
}

class AutoValue_Foo extends Foo {  // generated
  ...
  static class Builder extends Foo.Builder {
    private String userName;
    @Override
    public Builder setUserName(String userName) {
      this.userName = userName;
      return super.setUserName(userName);
    }
    ...
  }
}

```

I'm concerned, though, that this model is a bit tricky and might be a bit harder to follow than the current one.

**Comment by facboy** [comment]
I think what would be nice from my point of view would be that if auto-value found a matching getter method on the builder then it would assume that the abstract class would be entirely responsible for returning a value from that getter.  I.e. auto-value wouldn't validate that there was a matching setter, it would find a matching concrete getter and in effect say, 'Hey, you're on your own now,' and it would just delegate to that getter in the generated build/autoBuild method.

The particular case I'm trying to handle is where I have a nested AutoValue'd class inside a top-level AutoValue'd class.  I would like to be able to generate a set of builders for these, where the builder for the top-level class accepts a builder for the nested class in lieu of the nested-class itself.  It allows me to have a parallel builder structure that I can apply transforms/validations/whatever to and then hit build() on the top-level builder and out comes my complete, immutable structure.

Though to be honest ideally I want the builder getter/setter to return/accept the builders, and have these matched to the property in the AutoValue'd class.

**Comment by eamonnmcmanus** [comment]
I am interested in your idea that a concrete getter means that the abstract Builder class is taking care of that property itself. It is simple and straightforward. I think I'd like to find another use for it than the subject of this issue. I feel as if there probably are such uses but I'm not finding them right now.

Concerning your second paragraph, we're thinking of generalizing the existing feature where if you have a property `abstract ImmutableList<String> getFoos()` then your builder, instead of `abstract Builder setFoos(ImmutableList<String> foos)`, can have `abstract ImmutableList.Builder<String> foosBuilder()`. The generalization would apply this wherever the class (like `ImmutableList`) has a nested class called `Builder` that has a `build()` method of the appropriate type; has a way to construct a `Builder` (like `ImmutableList.builder()`); and has a way to initialize the `Builder` with the contents of an existing instance (like `ImmutableList.Builder.addAll(ImmutableList)`).

**Comment by facboy** [comment]
thinking about it a little more, maybe methods with a annotated as supplying a particular field, rather than just getX, as otherwise it may restrict the interface that people could define on their builder (eg they may want a getX that behaves independently of the logic used to supply a value to autoBuild/build).

**Comment by eamonnmcmanus** [comment]
The latest snapshot supports having a getter of type `Optional<T>` in a builder, where the original property has type `T`. This is the proposal described [earlier](https://github.com/google/auto/issues/300#issuecomment-172992715). We're not currently planning to implement the idea of having concrete getters in builders as suggested by @facboy [above](https://github.com/google/auto/issues/300#issuecomment-202994416). Although it's powerful, it's also kind of tricky, and in particular requires understanding interactions between the handwritten code and the generated code, in a way we've generally tried to avoid.
