### ISSUE TITLE
AutoValue: Extensibility of library to generate side classes

### ISSUE THREAD

**Issue by rsertelon** [google/auto#303]
We use AutoValue in many of our (JAX-RS) APIs and find it really useful.

As our DTOs are sometimes used by GWT applications, we annotated them with the provided `@GwtCompatible(serializable = true)` annotation.

The serializers generation is great for GWT RPC, but we would like to use the Errai framework that has a nice JAX-RS client implementation and its own Marshalling API.

Do you think AutoValue could provide a SPI to generate other classes linked to the AutoValue generated classes just as you do with GWT RPC Serialization classes?

It would allow the community to provide serialization/mapping extensions to AutoValue. We'd like to write the Errai one, but others could be done (Kryo de/serializers for example).

**Comment by rharter** [comment]
I'm working on something similar for Gson, with an added factory class outside of AutoValue that references the AutoValue generated classes. The way I accomplish this is by creating an extension to generate the appropriate intermediate classes, but then also having a separate AnnotationProcessor in the extension package that will generate the additional classes. This provides a nice separation of concerns, giving me the ability to generate my own classes without complicating the value proposition of AutoValue.

**Comment by tbroyer** [comment]
@rharter What if `AutoValueExtension.Context` also exposed the `Filer`? An extension could then generate the additional class in its `applicable(Context)` method and then return false if it doesn't need to generate an intermediate class.

The alternative (which works today with no modification to AutoValue) is to "simply" write an annotation processor for the `@AutoValue` annotation, completely independent of the AutoValue processor itself. The only downside is that it would have to duplicate all the code that analyzes the classes to extract properties and their types (and, which is the most complex I think, their `Builder` with their setters); it wouldn't have to do most of the validation though, as that'd be taken care of by the AutoValue processor. FWIW, this is the approach I used in [Bullet•](https://github.com/tbroyer/bullet) which processes Dagger‡'s `@Component` annotations.

**Comment by rharter** [comment]
@tbroyer Filer is technically exposed via `AutoValueExtension.Context` since we expose the `ProcessingEnvironment`, so you could simply call `context. processingEnvironment().getFiler()` and away you go.

You second suggestion is exactly what I'm using in my current work on [auto-value-gson](https://github.com/rharter/auto-value-gson) to generate a single `TypeAdapterFactory` for all generated classes.  Not having the property information isn't an issue since I make the annotated classes implement an interface that provides their type adapter, which the extension creates.  

I think it's fitting that external classes shouldn't need intimate knowledge of the properties of the annotated class, since an extension could easily provide a factory method, or actual Factory, that could take care of that.

**Comment by tbroyer** [comment]
> @tbroyer Filer is technically exposed via `AutoValueExtension.Context` since we expose the `ProcessingEnvironment`

Ah right. I saw `ProcessingEnvironment` but somehow thought that it'd only provide the elements/types information; but indeed it also exposes the `Filter` (and `Messager` and options).

**Comment by rsertelon** [comment]
Thanks for your answers.

I see that we can use the existing Extension mechanism, but it seems a bit dirty as it was not really designed to generate side classes but rather sub-classes.

I will try to do as @rharter suggested, but I really think that a dedicated extension mechanism would be great :)

**Comment by eamonnmcmanus** [comment]
It is now possible for an extension to return null in order to indicate that it has generated no class for the AutoValue hierarchy. Since extensions have access to the ProcessingEnvironment, they can [get a `Filer`](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/ProcessingEnvironment.html#getFiler--) and use it to generate side classes.

**Comment by rsertelon** [comment]
@eamonnmcmanus As of which version is this possible? Thanks !

**Comment by eamonnmcmanus** [comment]
As of version 1.4-rc3, which I released just now. :-)
