### ISSUE TITLE
Builder chaining

### ISSUE THREAD

**Issue by jzillmann** [google/auto#306]
I want some of my builders not to expose properties setter for complex properties but the builders for those properties itself. This is the same thing you guys did for the guava immutable collections (https://github.com/google/auto/commit/0c2f481daabe4645b4aeac340b31f1b4d8022d09) but for any kind of builder.

Now the great thing is i can already do this! My code looks like this:

```
@AutoValue
public abstract class ManagerConfig implements Serializable {

    private static final long serialVersionUID = 1L;

    public abstract ResourceSettings resourceSettings();

    public abstract JvmSettings jvmSettings();

    public static Builder builder() {
        return new AutoValue_ManagerConfig.Builder();
    }

    @AutoValue.Builder
    public static abstract class Builder {

        private ResourceSettings.Builder _resourceSettingsBuilder;
        private JvmSettings.Builder _jvmSettingsBuilder;

        abstract Builder resourceSettings(ResourceSettings resourceSettings);

        public ResourceSettings.Builder resourceSettings() {
            if (_resourceSettingsBuilder == null) {
                _resourceSettingsBuilder = ResourceSettings.builder();
            }
            return _resourceSettingsBuilder;
        }

        abstract Builder jvmSettings(JvmSettings jvmSettings);

        public JvmSettings.Builder jvmSettings() {
            if (_jvmSettingsBuilder == null) {
                _jvmSettingsBuilder = JvmSettings.builder();
            }
            return _jvmSettingsBuilder;
        }

        abstract ManagerConfig autoBuild();

        public ManagerConfig build() {
            if (_resourceSettingsBuilder != null) {
                resourceSettings(_resourceSettingsBuilder.build());
            }
            if (_jvmSettingsBuilder != null) {
                jvmSettings(_jvmSettingsBuilder.build());
            }
            return autoBuild();
        }
    }
}
```

Now instead of doing this:

```
        ManagerConfig.Builder managerConfig = ManagerConfig.builder();
        managerConfig.resourceSettings(ResourceSettings.builder().memory(123).vcores(3).build());

        JvmSettings.Builder jvmSettings = JvmSettings.builder();
        jvmSettings.envVariablesBuilder().put("JAVA_HOME", "myHome");
        jvmSettings.heapFraction(0.34f);

        managerConfig.jvmSettings(jvmSettings.build());

        ManagerConfig build = managerConfig.build();
        assertThat(build.resourceSettings().memory()).isEqualTo(123);
        assertThat(build.resourceSettings().vcores()).isEqualTo(3);
        assertThat(build.jvmSettings().envVariables()).hasSize(1).containsEntry("JAVA_HOME", "myHome");
        assertThat(build.jvmSettings().heapFraction()).isEqualTo(0.34f);
```

I can do:

```
        ManagerConfig.Builder managerConfig = ManagerConfig.builder();
        managerConfig.resourceSettings().memory(123).vcores(3);
        managerConfig.jvmSettings().envVariablesBuilder().put("JAVA_HOME", "myHome");
        managerConfig.jvmSettings().heapFraction(0.34f);

        ManagerConfig build = managerConfig.build();
        assertThat(build.resourceSettings().memory()).isEqualTo(123);
        assertThat(build.resourceSettings().vcores()).isEqualTo(3);
        assertThat(build.jvmSettings().envVariables()).hasSize(1).containsEntry("JAVA_HOME", "myHome");
        assertThat(build.jvmSettings().heapFraction()).isEqualTo(0.34f);
```

(which i like somewhat more)

Now the question... 
Is there already any support for doing this more elegantly ? (Its a lot of boilerplate i have to add)
If not, would it be possible/meaningful to you, to add this kind of support ?

**Comment by eamonnmcmanus** [comment]
We have a similar issue internally. I'm copying its text here:

### BEGIN QUOTE
Today, you can write something like this:

```java
@AutoValue
public abstract class Foo {
  Foo() {}

  public abstract ImmutableSet<String> strings();

  public static Builder builder() {
    return new AutoValue_Foo.Builder();
  }

  public abstract Builder toBuilder();

  @AutoValue.Builder
  public abstract class Builder {
    Builder() {}
    public abstract ImmutableSet.Builder<String> stringsBuilder();
    public abstract Foo build();
  }
}
```

The return type of `stringsBuilder()` must be exactly `ImmutableSet.Builder<String>`. The proposal is that, instead, it could be any type `MyBuilder` which has these properties:

1. it has a visible no-arg constructor (for use in the generated `AutoValue_Foo.Builder()` constructor);
2. it has a visible method `addAll(T)` or `putAll(T)`, where `T` is assignable from `ImmutableSet<String>` (for use in the generated `AutoValue_Foo.Builder(Foo)` constructor);
3. it has a visible method `build()` whose return type is `ImmutableSet<String>`.

`ImmutableSet.Builder<String>` has all of these properties, so what works today would continue to work. But you could also define your own `MySetBuilder` like this:

```java
public class MySetBuilder<E> extends LinkedHashSet<E> {
  public ImmutableSet<E> build() {
    return ImmutableSet.copyof(this);
  }
}
```

Then you could change this line above:
```java
   public abstract ImmutableSet.Builder<String> stringsBuilder();
```
to this:
```java
    public abstract MySetBuilder<String> stringsBuilder();
```

Since `MySetBuilder` is a `Set`, user code can call `clear()`, `remove()`, and so on on it. Obviously everything above that says `ImmutableSet<String>` would apply mutatis mutandis to `ImmutableMap<K, V>` and so on.

There's even no reason why the `thingBuilder()` magic should apply only to `com.google.common.collect.Immutable*` types. Any builder that obeys the rules above would work. With a small tweak (extend rule (1) so that it also works if `MyBuilder`'s containing type has a static method `MyBuilder builder()`), it would even work for `@AutoValue` properties that are themselves `@AutoValue` classes.
### END QUOTE

Your case is covered by the last paragraph above. On rereading the text, though, I see it is missing a way to convert a nested `@AutoValue` instance into a builder, which is needed to support `toBuilder()` in the containing `@AutoValue` class. That is conventionally done through an abstract `toBuilder()` method which AutoValue implements. So the rules should be:

If an `@AutoValue` class `Foo` has a property defined like this:
```java
  public abstract Bar bar();
  // or:
  public abstract Bar getBar();
```
then `Foo.Builder` can have a method like this:
```java
    public abstract Bar.Builder barBuilder();
```
provided that `Bar` meets all of these requirements:

1. there is a class `Bar.Builder` with a no-arg constructor;
2. `Bar.Builder` has an instance method `Bar` build();
3. either:
   * `Bar` has an instance method `Bar.Builder toBuilder()`, or
   * `Bar.Builder` has an instance method `addAll(Bar)` or `putAll(Bar)`.

Requirement 3 could potentially only apply if `Foo` has a `toBuilder()` method. (It's too bad that `ImmutableSet` etc don't have their own `toBuilder()` methods so we wouldn't need the special case for `addAll`/`putAll`.)

The rules are a bit more complicated when `Bar` has type parameters. AutoValue actually fudges the treatment of those a bit today and would presumably continue to do so.

I will look into implementing this.

**Comment by andrewmunn** [comment]
This feature is called ["Sub Builders"](https://developers.google.com/protocol-buffers/docs/reference/java-generated#sub-builders) in Protocol Buffers.

I would love to see this added to AutoValue because it's very cumbersome to modify complex nested AutoValues. Why should Guava's collections be the only supported Sub Builder?

**Comment by eamonnmcmanus** [comment]
I'm actually working on this at the moment and it should be ready soon.

**Comment by corydolphin** [comment]
@eamonnmcmanus awesome to see that you implemented it! This will make a bunch of my builders much simpler. Is there any chance you could make a new release with this feature included? Would love to get my hands on the new bits without depending on a snapshot!

Thanks for all your hard work here :)

**Comment by hzsweers** [comment]
the last two (maybe 3) RC releases have had them
