### ISSUE TITLE
Update Maven instructions

### ISSUE THREAD

**Issue by msfe** [google/auto#310]
In the readme.md you should update your Maven instructions.

${version} is deprecated and should be updated with ${project.version}. Changed it up below:

<dependencies>
  <dependency>
    <groupId>com.google.auto.service</groupId>
    <artifactId>auto-service</artifactId>
    <version>${project.version}</version>
    <optional>true</optional>
  </dependency>
</dependencies>

**Comment by tbroyer** [comment]
`${project.version} is not appropriate: you don't want to use your own project's version as the version for the auto-service dependency. The `${version}` placeholder in the README is just a way to communicate that you should provide the version of the dependency (i.e. don't put a version in the README that would need to be updated every time a release is cut). Possibly it could use`${auto-service.version}` instead of just `${version}` if the latter is confusing; or use `VERSION` or `[VERSION]` (the latter being purposefully invalid) with text saying you should change it.

**Comment by msfe** [comment]
Oh, sorry about that. Then i understand how it's supposed to be used, the
notation got me confused though so I would still prefer an update as you
described.
