### ISSUE TITLE
AutoValue: Inconsistent removal of consumed properties

### ISSUE THREAD

**Issue by gabrielittner** [google/auto#327]
The removal for AutoValue itself compares the returned property names with the method name ([AutoValueProcessor.java#L391](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/AutoValueProcessor.java#L391)), while the removal for extensions ([AutoValueProcessor.java#L440](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/AutoValueProcessor.java#L440)) compares it with the property key. Those two aren't the same when the methods are prefixed with get.

It's easy to workaround that by just returning both in `consumeProperties(Context)`.

**Comment by eamonnmcmanus** [comment]
I've rewritten this code substantially in the latest version, which hasn't been pushed to github yet. I believe it will behave correctly regardless of whether properties are prefixed or not. I'll ping this issue once that code is live so that you can confirm that the problem you are seeing has been fixed.

**Comment by gabrielittner** [comment]
It's fixed in the latest snapshot 👍
