### ISSUE TITLE
AutoValue with Polymorphic Serialization issue

### ISSUE THREAD

**Issue by nlenoire** [google/auto#329]
Hi,

I'm using google AutoValue to implement POJOs I want to serialize using Jackson. Some of my POJOs are using polymorphism. For them, I'm using the JsonTypeInfo + JsonSubTypes annotation with a property as type info. 

However, Jackson ignores the type name I set, and always use the class name as class indicator. I can workaround this issue by using @JsonTypeName on each of my sub-types, but I don't like this since I'm required to squatter the JSON ser/deser configuration.

Here is an example:
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
	@JsonSubTypes.Type(value = ConcreteType1.class, name = "type1"),
	@JsonSubTypes.Type(value = ConcreteType2.class, name = "type2")
})
static interface AbstractType {
		
}
	
@AutoValue
static abstract class ConcreteType1 implements AbstractType {
		
	public static ConcreteType1 create(String value) {
		return new AutoValue_ConcreteType(value);
	}
				
	public abstract String getMyProperty();
}

...
```
```java
new ObjectMapper().writeValueAsString(ConcreteType1.create("aValue"));
```
will produce

```
{
   "type": "AutoValue_ConcreteType1",
   "myProperty": "aValue"
}
```
instead of

```
{
   "type": "type1",
   "myProperty": "aValue"
}
```
Is it a bug ? Am I doing something wrong ?

Thanks,

**Comment by rharter** [comment]
This sounds like a Jackson issue, as it seems to deal with how their Annotation processes classes.

**Comment by tbroyer** [comment]
How about using `AutoValue_ConcreteType1.class` in `@JsonSubTypes.Type` instead of `ConcreteType1.class`? (assuming all classes are in the same package; if that's not the case, it seems like you should be able to put another `@JsonSubTypes` on `ConcreteType1` pointing to `AutoValue_ConcreteType1`: "link" from `AbstractType` to `ConcreteType1` without `name`, then from `ConcreteType1` to `AutoValue_ConcreteType1` with `name="type1"`)

But I agree that you're more asking for support about how to properly use Jackson with this setup, than having an issue with AutoValue proper.
