### ISSUE TITLE
Extensions should be able to apply to Builders as well

### ISSUE THREAD

**Issue by octylFractal** [google/auto#349]
I want to add some methods automatically to my `AutoValue` builder using an extension, but the `Builder` class in the parent is final so I can't extend it with more methods. I don't really care how it is implemented, but it would be really useful for me.

**Comment by eamonnmcmanus** [comment]
What sort of methods? Would they be methods that the user of the builder would want to call? In that case you'd want to declare them in the `@AutoValue.Builder` class and you'd want them to be abstract, I suppose. However the extension mechanism currently doesn't give you a way to consume abstract methods from builders, which means they would produce a compilation error.

**Comment by kenzierocks** [comment]
Yes, they are user-facing methods.

**Comment by JakeWharton** [comment]
Can you provide an example? I'm curious about some of the use cases.

**Comment by rharter** [comment]
As am I. I've been wondering for a while it if might make sense for the builders in general to be an extension, instead of a built in feature, even if a first party included extension.

**Comment by kenzierocks** [comment]
Here's a use case similar to mine: [Packets based on AutoValue](https://github.com/kenzierocks/PacketAutoValue).

Notice how in `Packet.Creator` I had to comment out [this line](https://github.com/kenzierocks/PacketAutoValue/blob/master/src/main/java/me/kenzierocks/pav/Packet.java#L10) since I couldn't consume the method.

If you run the test, you'll find that this still doesn't compile because I can't inherit from the parent builder.

One of the solutions to this is to not use the excellent builder code already there and generate my own.  Another is to make `readPacket` a static method on the `Packet` class, but then I lose inheritance and the ability to pass in an arbitrary `Packet.Creator` to a method that uses `readPacket`. I think the easiest and cleanest solution is to allow extending the builder as well.

**Comment by eamonnmcmanus** [comment]
So, today the generated Builder implementation class is final. I don't think there's a compelling reason for it to be, and if it were not then extensions could easily subclass it. That would fix half the problem. The other half would be allowing extensions to consume abstract builder methods, which while not too hard is not nearly as trivial. If we do the first half then there is a somewhat ugly workaround for people running into problems like this. Instead of having additional abstract methods in the Builder (like `readPacket` in the example), they would be concrete methods that the extension overrides.

**Comment by kenzierocks** [comment]
Yes, and the latter could be accomplished by doing something like:
```java
default readPacket(...) {
    throw new AbstractMethodError();
}
```
That would work temporarily, but would probably be a bit ugly.

**Comment by eamonnmcmanus** [comment]
I think this is obsolete. We no longer make the generated `Builder` class final if there are extensions, and additionally we provide support methods to make it easier for extensions to know what's in the user-written `@AutoValue.Builder` class.
