### ISSUE TITLE
Change name.

### ISSUE THREAD

**Issue by argestes** [google/auto#358]
This name made me think that this repo is about Android Auto

**Comment by rharter** [comment]
Google does more than just Android.

**Comment by eamonnmcmanus** [comment]
The name clash is unfortunate, but probably inevitable given that "auto" is such a common word. Changing the project name now would be very disruptive compared to the relatively small risk of confusion. The home page says "A collection of source code generators for Java" at the very top so anyone thinking it is something else should quickly realize their mistake.

**Comment by argestes** [comment]
I'm sorry if I sounded too arrogant. But this is how issue and ticket system mostly works in GitHub as you know.

I already knew your approach wasn't going to be like "Since someone requested let's change everything" and I know Google does more than just Android.

What I want to solve with this ticket is the problem of name clashing between Android Auto and Google Auto. Since Google is heavily working to promote Android in every way possible and since we all use smartphones Google means Android for most of us.

**Comment by cgruber** [comment]
For what it's worth we have a discussion in which we are leaning towards
separating the auto projects into separate projects which should, if we
arrive at a consensus, ease this problem.

That said, "Google means Android for a lot of us"... Except for all the
server side developers who use guava and otherwise.

At any rate, the point is reasonable. The insistence is less so.
Especially since it is immediately clear upon initial look at the readme
that this is not what was intended by someone searching for Android auto.
