### ISSUE TITLE
Allow @Memoized to take parameters

### ISSUE THREAD

**Issue by bemusementpark** [google/auto#391]
Memoized methods could/should be able to take parameters.

> A memoized function "remembers" the results corresponding to some set of specific inputs. 

https://en.wikipedia.org/wiki/Memoization#Overview

My first thought was that this kind of functionality could be implemented as a new extension, but  `@Memoized` is the perfect name for the functionality I have in mind.

Memoization generally requires a lot of boilerplate and we don't have something simple like python's `lru_cache` https://docs.python.org/3/library/functools.html#partial-objects

If arguments are hashed and added together (with appropriate multipliers) then they could be used to create a `HashMap<Integer, T>` and a value given to `@Memoized` could specify the max size or not (i.e. infinite).

Could this functionality (with or without bounds on cache size) be added to `@Memoized`?

**Comment by cdeszaq** [comment]
`@Memoized` could, by default, use a `HashMap` if it's given a max size or something (encouraging unbounded caching is probably not a great idea).

Additionally, having another param to take a class to use as a cache would allow extending and supporting other impls if needed.

**Comment by bemusementpark** [comment]
Indeed. So use http://chriswu.me/blog/a-lru-cache-in-10-lines-of-java/
```
public LRUCache<K, V> extends LinkedHashMap<K, V> {
  private int cacheSize;

  public LRUCache(int cacheSize) {
    super(16, 0.75, true);
    this.cacheSize = cacheSize;
  }

  protected boolean removeEldestEntry(Map.Entry<K, V> eldest) {
    return size() >= cacheSize;
  }
}
```

**Comment by ronshapiro** [comment]
Does this work for you?

```java
@AutoValue
abstract class SuperInt {
  abstract int value();
  
  @Memoized
  protected Map<Integer, SuperInt> adderCache() {
    return new HashMap<>();
  }
  
  // "@Memoized"
  SuperInt performAdd(int operand) {
    return adderCache().computeIfAbsent(operand, k -> SuperInt.create(k + value()));
  }
}
```

**Comment by netdpb** [comment]
`@AutoValue` is designed to support immutable value types. `@Memoized` just helps to make derived properties more performant. It's not intended to support general memoization.

An `@AutoValue` class author could certainly add more sophisticated memoization using `Map.computeIfAbsent()` or [Guava's cache](https://github.com/google/guava/wiki/CachesExplained) or [Caffeine](https://github.com/ben-manes/caffeine), but I think we want to keep `@AutoValue`'s feature set as simple as we can.

I'm closing this feature request (it hasn't been updated since 2016 anyway), but feel free to reopen if you feel strongly.
