### ISSUE TITLE
generated 'equals()' methods with full packagename for java 'object'

### ISSUE THREAD

**Issue by Bodo1981** [google/auto#403]
current implementation:

```
@Override
public boolean equals(Object o) {
   if (o == this) {
      return true;
   }
   if (o instanceof Foo) {
      Foo that = (Foo) o;
      return (this.foo == that.foo());
   }
   return false;
}
```

if you have declared a class or interface which is named 'Object' in the same package the generated autovalue will not compile (in case of interface) because your custom 'Object' class/interface will be used instead of the java 'Object' class

the generated class should use the following equals() implementation with the full package name of the java 'Object'

```
@Override
public boolean equals(java.lang.Object o) {
   if (o == this) {
      return true;
   }
   if (o instanceof Foo) {
      Foo that = (Foo) o;
      return (this.foo == that.foo());
   }
   return false;
}
```

**Comment by eamonnmcmanus** [comment]
If you have a class called Object you are going to have no end of trouble. Similarly, if you have a class called String the generated toString() method would have to return java.lang.String. By reusing these common names you are just generating confusion for people reading your code, including most likely your future self.

We *could* fix this, but currently that would mean one of two things: either we uglify the generated code by using fully-qualified names, even though they're not needed in the vast majority of cases; or we complicate the AutoValue code to detect when there is a local class called Object and use the fully-qualified spelling if so. We do in fact do that for java.util.Arrays (see [here](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/AutoValueProcessor.java#L756) and [here](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/autovalue.vm#L87)) but even that is probably overkill.

Having said all that, I do have a long-term plan to change the way that imports are handled so that the [template](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/autovalue.vm#L115) might say something like this:
```
public boolean equals(`java.lang.Object` o) {
```
and it would appear as `Object` or `java.lang.Object` in the generated code, as appropriate.

**Comment by gk5885** [comment]
FWIW, this is the sort of thing that you get for free with JavaPoet.

**Comment by ekuefler** [comment]
Couldn't you also do an explicit import of `java.lang.Object` and `java.lang.String`? This at least restricts the uglification to the imports block.

**Comment by tbroyer** [comment]
FWIW, this is what JavaPoet does by default.

There are two issues here: naming conflicts when both classes are used in the same generated class, and need to be disambiguated; and conflicts when the same-package `Object` exists (or **will** exist!) but is not used. For the latter case, explicitly importing `java.lang.Object` and `java.lang.String` is enough; for the former, you need to track usage and detect conflicts. And yes, you get both things "for free" with JavaPoet.

**Comment by eamonnmcmanus** [comment]
Unfortunately JavaPoet has its own problems, for example when Object is a nested class inside an ancestor of the generated class.

**Comment by JakeWharton** [comment]
That's also true of the template approach though, right? It's a fixed
problem regardless of strategy. Also JavaPoet is in a position to fix this
automatically since we can inspect all ancestors.

**Comment by eamonnmcmanus** [comment]
No, it's not true of the template approach since we can have [custom logic](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/TypeSimplifier.java#L92) for imports, using what we know about where the generated code will be used. This is as opposed to the fixed logic that JavaPoet uses. It's true that that fixed logic could look at supertypes, and that would probably work for AutoValue, but in the general case the supertypes themselves might not exist when JavaPoet is running.

**Comment by eamonnmcmanus** [comment]
A fix is in the works. The "long-term plan" I mentioned in my first comment has been completed, so it is now possible to have `` `java.lang.Object` `` in the templates and have it resolve to `Object` if that is unambiguous or `java.lang.Object` if not. But this only works if both `Object`s are referenced in the code. As @tbroyer mentioned, there is also the case where the code references `java.lang.Object` but not the `com.example.Object` class that is lurking in the same package as the `com.example.AutoValue_Foo` that we are generating.

JavaPoet avoids this problem by treating `java.lang` the same as any other package, so it will import `java.lang.Object` explicitly even though that is almost never necessary. (It has an option to disable this, but then you are vulnerable to the problem described here.) The fix I am proposing produces cleaner code, in my opinion. If you reference `java.lang.Object`, we look to see if `com.example.Object` exists, and if it does we output the fully-qualified name `java.lang.Object`. In the vastly more usual case where `com.example.Object` does not exist, we output plain `Object` without importing anything.

It is still true that people should avoid reusing names from `java.lang`. [Error Prone](http://errorprone.info/) has a [check](https://github.com/google/error-prone/blob/master/docs/bugpattern/JavaLangClash.md) for this, which if it had existed at the time might have led to [`com.google.testing.compile.Compiler`](https://github.com/google/compile-testing/blob/master/src/main/java/com/google/testing/compile/Compiler.java) being called something else. (Did you know there was a `java.lang.Compiler`?)

**Comment by tbroyer** [comment]
> If you reference `java.lang.Object`, we look to see if `com.example.Object` exists, and if it does we output the fully-qualified name `java.lang.Object`. In the vastly more usual case where `com.example.Object` does not exist, we output plain `Object` without importing anything.

Note that `com.example.Object` might not yet exist at the time you check for its existence (could be created by a later annotation processing round, or a later compilation step of other sources, or simply "assembled" at runtime from a separate JAR –such split packages now discouraged in the Java 9 era, but they still exist, if only for tests)

**Comment by eamonnmcmanus** [comment]
@tbroyer that is absolutely correct. However we're then broken only when three unlikely things happen together: (1) someone makes a class called `Object` (why would you do that); (2) it is not present on initial compilation; (3) it is not referenced in the `@AutoValue` class. In the very improbable case that someone manages to make all three things happen, I will unsympathetically suggest that they fix at least one of them.

**Comment by tbroyer** [comment]
> In the very improbable case that someone manages to make all three things happen, I will unsympathetically suggest that they fix at least one of them.

I do not disagree :wink:
