### ISSUE TITLE
Should annotations also propagate to generated builders?

### ISSUE THREAD

**Issue by ZacSweers** [google/auto#409]
Sort of a proposal: I noticed `CopyAnnotations` only propagates to the generated class methods but does not propagate builder method parameters. We actually get warnings in the IDE on builders along the lines of "overriding methods do no match annotations".

**Comment by eamonnmcmanus** [comment]
Interesting. We already copy method annotations from the abstract property-getter methods in the `@AutoValue` class to their generated implementations, and `@CopyAnnotations` serves to *prevent* that where necessary. I think it would make sense to do the same thing for annotations on builder methods, both getters and setters.

What are the specific annotations where you are seeing this problem?

**Comment by hzsweers** [comment]
We enforce null ability annotations on both sides (nullable and NonNull), but the NonNull annotations aren't copied over in the implemented builders. I didn't realize copyannotations was just to have an exclusion list though, that makes sense.

**Comment by eamonnmcmanus** [comment]
It's kind of a legacy thing: CopyAnnotations is for exclusion on methods, but for inclusion on the `@AutoValue` class itself, because that's compatible with how things worked before it was introduced.

**Comment by hzsweers** [comment]
Hmm, should I rename this to "should annotations be copied into generated builders"?

**Comment by eamonnmcmanus** [comment]
Sounds like a better description, yes.

**Comment by PhilippWendler** [comment]
I have the problem that I need to annotate some builder methods with `@SuppressWarnings` in order to avoid google/error-prone#495, so I also would like to see this added.

**Comment by eamonnmcmanus** [comment]
OK, though that looks like a bug in Error Prone. If AutoValue is generating methods that legitimately provoke Error Prone warnings, I think we would want to fix that rather than just allowing people to suppress those warnings.

**Comment by ibwhite** [comment]
Here's a usecase for copying builder method annotations that I ran into today:

If you are using Jackson, and you are adopting @eamonnmcmanus's suggestion for unsetting Optionals from builders (laid out [here](https://github.com/google/auto/issues/384#issuecomment-249997998)) in which we create two identically-named builder methods for each field, then Jackson will get confused about which builder method it's supposed to use.

The (I think) preferred solution is to annotate the builder methods with `@JsonProperty` so I can specify which one Jackson's supposed to use. But since `@JsonProperty` isn't copied to the generated class, I'm running into some situations where Jackson is erroring on "conflicting setter definitions" and I have no ability to fix it short of a hacky mixin or something.

For the time being I guess I'm going to try the workaround of naming the "optional" version of the builder methods with a different prefix, but it's a little awkward and pollutes all my downstream code unnecessarily. It'd be nice if the annotations propagated so I didn't have to do this.
