### ISSUE TITLE
Proposal: Expose read-only builder properties in Extensions API

### ISSUE THREAD

**Issue by ZacSweers** [google/auto#421]
Hey all,

I've run into a few cases now where an extension implementation would be improved by being builder-aware (so it can generate code calling into it). What would you think of exposing this in a read-only fashion in the extensions API?

**Comment by eamonnmcmanus** [comment]
That occurred to me recently as well. Since the class generated by an extension is a descendant of the AutoValue implementation, it inherits the generated Builder and can call it. My main concern is that builders are a lot more variable than what they build, so the API by which the contents of a builder might be exposed could be trickier. A minimal API would be just to tell the extension what the `@AutoValue.Builder` class is (to save it having to search), but then leave it to fend for itself when it comes to figure out how to build stuff. Things like `Optional` properties and nested builders mean this isn't necessarily trivial.

Could you describe some of the cases where this would have been useful?

**Comment by hzsweers** [comment]
Here's an example: https://github.com/rharter/auto-value-gson/pull/89

**Comment by eamonnmcmanus** [comment]
Suppose you had access to a `Map<String, Set<ExecutableElement>>` that told you what setters or builders there were for each property. Would that help? So for example given this...

```java
@AutoValue
abstract class Foo {
  abstract ImmutableList<String> strings();
  abstract Optional<Thread> thread();

  @AutoValue.Builder
  abstract static class Builder {
    abstract Builder setStrings(List<String> strings);
    abstract ImmutableList.Builder<String> stringsBuilder();
    abstract Builder setThread(Optional<Thread> thread);
    abstract Builder setThread(Thread thread);
    abstract Foo build();
  }
}
```

...the API would given you a Map where `"strings"` maps to the `setStrings` and `stringsBuilder` methods, and `"thread"` maps to the two `setThread` methods.

You'd still be a bit on your own to figure out what each kind of method is, and I'm afraid that extensions might be a bit fragile if we add new variants of setters that didn't exist when the extensions were written.

**Comment by hzsweers** [comment]
hmm, yeah that could work. I think ideally it would give a reference to the `Builder` class itself, but not the worst thing in the world if they just required consumers to expose an entry point for instantiation in some "known location".

**Comment by aurae** [comment]
FWIW, this proposal would also allow for the integration of `Optional` types from third-party libraries as described [here](https://github.com/google/auto/issues/278#issuecomment-294007719). An extension could then provide the mapping functions for non-Java8-or-Guava fields in the `@AutoValue` class, consume those properties & take them away from the default code generation path for `Builders`.

**Comment by bryanstern** [comment]
@eamonnmcmanus I'm thinking of taking a crack at this. Is there any work in this area that might make my efforts for naught?

**Comment by eamonnmcmanus** [comment]
@bryanstern Nobody is working on this currently to my knowledge. But a first step would be to have a detailed API proposal (perhaps based on my Jan 1 suggestion above) and run it through Google's internal API review process.

**Comment by bryanstern** [comment]
I'm unfamiliar with Google's API review process, could you point me to more info (style, where to submit, etc.)?

Basically we'd add an optional property to `AutoValueExtension.Context` that represents the builder.
```java
public interface AutoValueExtension.Context {
  ProcessingEnvironment processingEnvironment();
  String packageName();
  TypeElement autoValueClass();
  Map<String, ExecutableElement> properties();
  Set<ExecutableElement> abstractMethods();
  Optional<BuilderContext> builderContext(); // present if class has a builder
}

// represents an AutoValue builder class
public interface AutoValueExtension.BuilderContext {
  TypeElement builderClass();
  ExecutableElement buildMethod();
  Multimap<String, ExecutableElement> setters(); // multimap of properties to setters
  Map<String, TypeElement> propertyBuilders(); // map of properties to their builder type
  Set<String> requiredProperties(); // set of properties that are neither nullable nor optional
}
```

**Comment by eamonnmcmanus** [comment]
I would have to do the API review business. Your proposal looks like a promising starting point, although we wouldn't want to have the Guava class `Multimap` in the API. `java.util.Optional` is fine, though.

**Comment by hzsweers** [comment]
that API proposal looks good to me as well. Would be happy to help test a prototype of it in the auto-value-gson/moshi extensions as well to look for pitfalls

**Comment by bryanstern** [comment]
After taking a shot at implementing this, I don't think it makes sense for `AutoValueExtension.Context` have a `AutoValueContext.BuilderContext` property. Instead we'd pass the a `BuilderContext` as an additional param to `AutoValueExtension#generateClass`. This is because `AutoValueProcessor` cannot validate the Builder until all extensions have indicated which properties and methods they will consume.

Also, I don't think an extension needs to know which properties are required. This is already enforced by AutoValue.

In summary the relevant changes are now simply:
```java
public abstract class AutoValueExtension {
  // represents an AutoValue builder class
  public interface BuilderContext {
    TypeElement builderClass();
    ExecutableElement buildMethod();
    Map<String, Set<ExecutableElement> setters(); // multimap of properties to setters
    Map<String, ExecutableElement> propertyBuilders(); // map of properties to their builder type
  }

  public abstract String generateClass(
      Context context, Optional<BuilderContext> builderContext, String className, String classToExtend, boolean isFinal);
}
```

**Comment by hzsweers** [comment]
That'd be a breaking API change wouldn't it? Might be hard to swing unless you can make it an optional overload

**Comment by eamonnmcmanus** [comment]
Adding a parameter to `generateClass` would break all existing extensions, so that's probably not going to work. Perhaps we could say that the `builderContext()` method cannot be called before `generateClass`, even though it is available within several of the other methods? Or, we could overload `generateClass` with two non-abstract methods, where the default implementation of the one with the `builderContext` parameter would be to call the one without it. Neither of those possibilities is all that attractive. :-/

**Comment by bryanstern** [comment]
Good point about the breaking API change.

I think overloading `generateClass`, having the default implementation forward the call to the original method, and deprecating the original method is the most promising option.

**Comment by eamonnmcmanus** [comment]
I'm finally picking this up, after two years. I used #501 as a starting point, though because the AutoValue implementation has changed a lot since then I had to redo the code changes. Here's what I'm thinking of as the API:

```java
public abstract class AutoValueExtension {
  public interface Context {
    ...

    /**
     * Returns a representation of the {@code Builder} associated with the {@code @AutoValue} class,
     * if there is one. This method will return {@link Optional#empty()} if called from within the
     * {@link #applicable} method. If an Extension needs {@code Builder}
     * information to decide whether it is applicable, it should return {@code true} from the
     * {@link #applicable} method and then return {@code null} from the {@link #generateClass}
     * method if it does not need to generate a class after all.
     *
     * <p>The default implementation of this method returns {@link Optional#empty()} for
     * compatibility with extensions which may have implemented this interface themselves.
     */
    default Optional<BuilderContext> builder() {
      return Optional.empty();
    }
  }

  /**
   * Represents a {@code Builder} associated with an {@code @AutoValue} class.
   */
  public interface BuilderContext {
    /**
     * Returns the {@code @AutoValue.Builder} interface or abstract class that this object
     * represents.
     */
    TypeElement builderType();

    /**
     * Returns static no-argument methods in the {@code @AutoValue} class that return the builder
     * type.
     *
     * <p>Consider a class like this:
     * <pre>
     *   {@code @AutoValue} abstract class Foo {
     *     abstract String bar();
     *
     *     static Builder builder() {
     *       return new AutoValue_Foo.Builder()
     *           .setBar("default bar");
     *     }
     *
     *     {@code @AutoValue.Builder}
     *     abstract class Builder {
     *       abstract Builder setBar(String x);
     *       abstract Foo build();
     *     }
     *   }
     * </pre>
     *
     * <p>Here {@code builderMethods()} will return a set containing the method
     * {@code Foo.builder()}. Generated code should usually call this method in preference to
     * constructing {@code AutoValue_Foo.Builder()} directly, because this method can establish
     * default values for properties, as it does here.
     */
    Set<ExecutableElement> builderMethods();

    /**
     * Returns the method {@code build()} in the builder class, if it exists and returns the
     * {@code @AutoValue} type. This is the method that generated code for
     * {@code @AutoValue class Foo} should call in order to get an instance of {@code Foo} from its
     * builder. The returned method is called {@code build()}; if the builder uses some other name
     * then extensions have no good way to guess how they should build.
     *
     * <p>A common convention is for {@code build()} to be a concrete method in the
     * {@code @AutoValue.Builder} class, which calls an abstract method {@code autoBuild()} that is
     * implemented in the generated subclass. The {@code build()} method can then do validation,
     * defaulting, and so on.
     */
    Optional<ExecutableElement> buildMethod();

    /**
     * Returns the abstract build method. If the {@code @AutoValue} class is {@code Foo}, this is an
     * abstract no-argument method in the builder class that returns {@code Foo}. This might be
     * called {@code build()}, or, following a common convention, it might be called
     * {@code autoBuild()} and used in the implementation of a {@code build()} method that is
     * defined in the builder class.
     *
     * <p>It is usually better to use the method returned by {@link #buildMethod()} if it exists,
     */
    ExecutableElement autoBuildMethod();

    /**
     * Returns a map from property names to the corresponding setters. A property may have more than
     * one setter. For example, an {@code ImmutableList<String>} might be set by
     * {@code setFoo(ImmutableList<String>)} and {@code setFoo(String[])}.
     */
    Map<String, Set<ExecutableElement>> setters();

    /**
     * Returns a map from property names to property builders. For example, if there is a property
     * {@code foo} defined by {@code abstract ImmutableList<String> foo();} or
     * {@code abstract ImmutableList<String> getFoo();} in the {@code @AutoValue} class,
     * then there can potentially be a builder defined by
     * {@code abstract ImmutableList.Builder<String> fooBuilder();} in the
     * {@code @AutoValue.Builder} class. This map would then map {@code "foo"} to the
     * {@link ExecutableElement} representing {@code fooBuilder()}.
     */
    Map<String, ExecutableElement> propertyBuilders();
  }
```

The main differences compared to what we had before:

* Using `Optional<BuilderContext>` rather than having a separate method to tell whether there is a builder. (I think back in 2017 we were still keeping Java 7 compatibility so we couldn't use `Optional`.)

* New method to return the static `builder()` methods from the `@AutoValue` class, or more accurately all visible static no-arg methods that return the `@AutoValue.Builder` type.

* Separate `buildMethod()` and `autoBuildMethod()` getters. The former always returns a method called `build()`, which is generally the one that the extension should call if it is building things. The latter is the method that the extension can override if it wants to do additional work before or after building.

The last point implies that the generated `Builder` class should no longer be `final`, at least when there are extensions generating subclasses.

My feeling is that this API is going to be enough to address _many_ but by no means all of the things that extensions might want to do with builders. We can add to it later, of course, but I think some extensions may end up imposing constraints, like "if you use this extension with an `@AutoValue` class then that class's builder can't use property builders" (or whatever).

**Comment by ZacSweers** [comment]
That API looks good to me 👍

**Comment by bryanstern** [comment]
+1 to what Zac said. I think this will support the existing use cases I've seen requested in other AutoValue extension projects.

**Comment by bryanstern** [comment]
Do you have any estimate when we might see this land or if you could send me a preview build? Would love to update https://github.com/rharter/auto-value-gson/pull/136 ASAP.

**Comment by eamonnmcmanus** [comment]
I have made a provisional API and implementation but the API still needs to go through Google's internal API review process. If you want to bet that the result of that process will not be substantially different, you could experiment with [this snapshot](https://github.com/eamonnmcmanus/auto/tree/builderapi). No guarantees, though.

I'm hoping to publish something definitive in the next few weeks.

**Comment by eamonnmcmanus** [comment]
The API has been reviewed and is essentially unchanged. I've released [1.7rc1](https://repo1.maven.org/maven2/com/google/auto/value/auto-value/1.7rc1/) which includes it. If bryanstern@ or anyone else can confirm that this works with existing extensions, I'll promote 1.7rc1 to plain 1.7.

**Comment by bryanstern** [comment]
I'm currently working on updating the auto-value-gson extension. I'll keep you updated.

**Comment by bryanstern** [comment]
I have an extension working with it. The only rough edges I ran into were:
1) `context#builderContext` not being present in the `context` provided to `AutoValueExtension#applicable`. Might be worth calling this out in the javadoc as I recall there was some reason it could not be provided at that point.
2) It would be nice to have a field in `BuilderContext` that returns the `TypeElement` for the concrete `Builder` type. This would make instantiating a builder via its constructor more convenient.

**Comment by eamonnmcmanus** [comment]
Great news! I think I'll go ahead and release a 1.7 in the very near future, then.

Concerning the remarks:

1. I think [we do](https://github.com/google/auto/blob/86f456371a23353acfa6dc5aacf880eb10439fad/value/src/main/java/com/google/auto/value/extension/AutoValueExtension.java#L151) already document this, don't we? It's definitely annoying, though. The issue is that we can't know which methods are property methods until we have given extensions a chance to claim abstract methods that are *not* property methods. That means we can't construct a correct `BuilderContext` before that point, and in particular before calling `applicable`. We *might* be able to work around this restriction in some approximate way, but I think the documented way for extensions to avoid the problem is better. (I wish we'd had this returning-null behaviour from the outset, and we hadn't included `applicable` at all.)

2. It isn't really possible to return the `TypeElement` for the concrete `Builder`, since it hasn't been compiled at the point the extension is being called. Both the concrete `Builder` class and whatever code the extension generates will be compiled at the same time. It would be possible to defer compilation of extension code to the next round, so that the original AutoValue-generated code had already been generated at that point, but I think that would be fragile and liable to break existing extensions.

**Comment by bryanstern** [comment]
Good points and you're right about the documentation. I was looking at the `AutoValueExtension#applicable` javadoc. Might be worth calling out that the `Context` provided may differ from the `Context` passed to `generateClass`?
