### ISSUE TITLE
Generate Builder with constructor arguments

### ISSUE THREAD

**Issue by rileymacdonald** [google/auto#429]
Is it possible to have AutoValue generate a `Builder` with required constructor arguments? I'm looking to refactor existing immutable value classes in my API which use the `Builder` pattern. The following is an example of an external call to an `Animal` class which requires a name:

Existing external API where `name` "dog" is required:
`Animal dog = Animal.Builder("dog").setNumberOfLegs(4).build();`

The reason I'm looking for this is because I'm unable to make API changes at this time. I'd like to take advantage of AutoValue but I've yet to find a clean way around this.

**Comment by eamonnmcmanus** [comment]
The example is not completely clear. If `Builder` is a static method, like this:
```java
Animal dog = Animal.builder("dog").setNumberOfLegs(4).build();
```
then it is straightforward to define such a method, and have it call `setName(name)` on the new builder before returning it. On the other hand, if `Animal.Builder` is a constructor call, we don't provide a way to do that, with or without parameters, since the actual constructor is `AutoValue_Animal.Builder` and you don't want to expose that to callers.

**Comment by rileymacdonald** [comment]
Thanks, this answers my question. This issue can now be closed.
