### ISSUE TITLE
MutableGraph is incompatible with AutoValue.Builder

### ISSUE THREAD

**Issue by cgrushko** [google/auto#441]
That is, I can't write something like this:

```java
@AutoValue
abstract class Foo {

  abstract ImmutableGraph<BuildRule> graph();

  @AutoValue.Builder
  abstract static class Builder {
    abstract MutableGraph<BuildRule> graph();
    public abstract Foo build();
  }

}
```

Because 

    Method looks like a property builder, but it returns com.google.common.graph.MutableGraph which does not have a non-static build() method

**Comment by cgrushko** [comment]
@jrtom

**Comment by eamonnmcmanus** [comment]
Did you mean this?

```java
@AutoValue
abstract class Foo {

  abstract ImmutableGraph<BuildRule> graph();

  @AutoValue.Builder
  abstract static class Builder {
    abstract MutableGraph<BuildRule> graphBuilder();  // not graph()
    public abstract Foo build();
  }
}
```

I think this is conceptually very similar to the idea that you can't use a `Set` as a builder for an `ImmutableSet`. You have to use `ImmutableSet.Builder`. Perhaps for consistency with other com.google.common classes, `ImmutableGraph` should have a nested `Builder` class? But that would be inconsistent with the existing `GraphBuilder` class, which is not used to build up entries in a Graph but rather to define the overall properties of a new empty graph, such as whether it is directed.

**Comment by jrtom** [comment]
@cgrushko Not quite sure what you're trying to accomplish, but I think that it's something like this:

You want to have a Foo with an ImmutableGraph as a member, accessed via graph().

You want a Builder that will generate a Foo object, including its ImmutableGraph member, based on a MutableGraph that you supply to the Builder.

As @eamonnmcmanus points out, you can't supply a MutableGraph and have it automatically convert to an ImmutableGraph, because AutoValue doesn't know how that would work.

The only way you can (currently) get an ImmutableGraph instance is as follows:

    ImmutableGraph graph = ImmutableGraph.copyOf(mutableGraph);

That is, you can't build an ImmutableGraph from scratch; it doesn't have its own Builder.  (An earlier prototype of ImmutableGraph had such a Builder, but all it was actually doing was building up a MutableGraph instance internally and then converting its internal data structures to immutable ones when build() was called, so we decided that it was more honest to just provide a copyOf() method.)

Given that, in this context I wouldn't bother with the Foo.Builder class at all (unless you have other properties you also want to set); just provide a create(ImmutableGraph) method as usual for AutoValue:

     Foo.create(immutableGraph);

or

    Foo.create(ImmutableGraph.copyOf(mutableGraph));

Hope that helps.

**Comment by cgrushko** [comment]
Right - I have multiple attributes, that I use `AutoValue.Builder` for, and I want to add a graph to the class. 
I also want to be able to construct the graph in pieces, as opposed to passing it fully constructed at once. (similarly to having a `ImmutableSet.Builder<T>` as a "attribute" in the `Builder`).

I can see why it's infeasible using the current `MutableGraph` / `ImmutableGraph` design.

**Comment by jrtom** [comment]
If you want to be able to either construct the graph in pieces after the Foo object is created, and possibly also to provide ImmutableGraph which is a copy of the graph you've built, _and_ memoize that so that you aren't asking the user to rebuild the immutable copy every time it's asked for...

...then I'm not sure you want an AutoValue, which appears to be intended for immutable value objects.

**Comment by cgrushko** [comment]
I'm afraid we're talking past each other. A step back -

What I want is 
https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#accumulate
for graphs.

I understand how the current design works, and understand why it doesn't fit with `AutoValue.Builder`. I still want a solution :)

Right now `AutoValue.Builder` can't be used if I want a user to be able to incrementally construct a graph object in a builder.

**Comment by jrtom** [comment]
Ah, I think I see.  You want to be able to fluently build a graph, like this:

    graph.addNode(foo).addNode(bar).putEdge(foo, baz);

and then presumably make it Immutable.

I'm sure you're aware that you can build up the graph ahead of time (i.e., before you start invoking the Foo.Builder), so I assume that the main pain point is that you would prefer to be able to do those two things (build up the graph, and invoke the Foo.Builder) as part of the same process.

It is true that common.graph does not support that specific syntax.  I would be very interested to know whether there is some specific use case that this means that we don't support well, or whether it's mostly a matter of preferring that syntax.  (Either way it's good feedback.  :) )

If I'm still off-base, then probably the best thing would be for us to discuss this off-thread.

**Comment by cgrushko** [comment]
Yes. I'll emphasize - I want to be able to do 

```java
Foo.Builder builder = Foo.builder();
builder.someListBuilder().add("bla"); // This is already supported
builder.someGraphBuilder().putEdge(...); // This is what I want
builder.build(); // build() automatically makes an immutable copy of someGraphBuilder() 
```

**Comment by jrtom** [comment]
OK, you want the "builders all the way down" syntax.  :)  Got it.

I don't think that we're likely to do this soon.  We've discussed providing Builders to the Immutable* common.graph classes, but (as I noted earlier) we experimented with this a while back and there didn't seem to be much demand for it at the time (and it's a bit tricky to do correctly in any other way than just constructing a mutable graph and then copying it).

**Comment by eamonnmcmanus** [comment]
To be clear, this would work *if* `ImmutableGraph` had a static `builder()` method that returned `MutableGraph` and *if* `MutableGraph` had a `build()` method that returned `ImmutableGraph`. I don't think those would make sense in the current API, though.

You could make something not too horrible without changing the common.graph API, by making an `ImmutableGraphBuilder` class externally, that perhaps implements `MutableGraph` and perhaps wraps an existing `MutableGraph` implementation. If `ImmutableGraphBuilder` has a public no-arg constructor and a public `ImmutableGraph build()` method, that would be enough. You would still not be able to have AutoValue implement a `Foo.toBuilder()` method for you, though, since `ImmutableGraph` doesn't have a method `ImmutableGraphBuilder toBuilder()`.

[Reference](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#nested_builders)

**Comment by eamonnmcmanus** [comment]
I don't think this is a bug or feature request in AutoValue, so I'm closing it. Please log a bug against `com.google.common.graph` instead.
