### ISSUE TITLE
Drop AutoValue support for Java 6

### ISSUE THREAD

**Issue by eamonnmcmanus** [google/auto#448]
The current AutoValue version (1.4rc3) supports Java 6 completely. That means that it can be compiled on Java 6, run on Java 6, and generates code that can itself be compiled on Java 6. This was valuable in the past because many Android developers were limited to Java 6. At this point, though, only [12.6%](https://developer.android.com/about/dashboards/index.html) of Android devices are running Android 4.3 or earlier. I think it would make sense to drop Java 6 support after AutoValue 1.4 is released. People who still do need to use AutoValue on those early Android versions could still use AutoValue 1.4 but would not be able to use later versions of AutoValue.

For reference, Java 7 was released in [July 2011](https://www.java.com/en/download/faq/release_dates.xml).

**Comment by ronshapiro** [comment]
It also seems unlikely that `@AutoValue` would use try-with-resources, which is the only java7 incompatible feature for the android build tools. 👍

**Comment by eamonnmcmanus** [comment]
Thanks, yes, I was going to mention that that has been the case [since 2013](http://tools.android.com/recent/androidstudio032released) so *probably* the generated code will continue to be usable on earlier platforms. But in addition to try-with-resources there's also the matter of the Java API. Unless we specifically put tests in place to ensure that the generated code doesn't use APIs that are new in Java 7, those may well creep in.

**Comment by eamonnmcmanus** [comment]
Post 1.4 we are dropping support for Java 6 completely, and for compiling with Java 7 javac. (We are still generating Java 7 compatible source code.)

**Comment by adriancole** [comment]
This will be a shame to do because autovalue is used implicitly for code in
java agents which support JRE 6. Iotw android isnt the only use case for
new code being java 6 compat.

If you chose to do this the whole zipkin java ecosystem of core libraries
would need to pin to an old autovalue or remove it.

**Comment by eamonnmcmanus** [comment]
I guess I'm wondering why Java agents would support JRE 6 in this day and age. Java 7 was released in 2011.

Although AutoValue's generated code still does compile on Java 6, we have given up testing that. So it will inevitably stop working at some point. There are a few places where the diamond operator in particular would be quite convenient.

**Comment by adriancole** [comment]
> I guess I'm wondering why Java agents would support JRE 6 in this day and age. Java 7 was released in 2011.

I think it is mainly APM vendors or OSS maintainers who want to help
with old apps. @felixbarny is that right?

> Although AutoValue's generated code still does compile on Java 6, we have given up testing that. So it will inevitably stop working at some point. There are a few places where the diamond operator in particular would be quite convenient.

agreed. and incidentally I *think* retrolambda should be fine as it
happens after auto-value on all classes. It would mainly be an issue
if JRE7+ apis were mandatory (animal sniffer could guard this perhaps)

**Comment by felixbarny** [comment]
Due to [plumbr](https://plumbr.eu/blog/java/java-version-and-vendor-data-analyzed-2016-edition), almost 10% of their customers have used Java 1.6 in 2016. Its up to the individual project maintainers to decide if they want to abandon 10% of their users or not. But of course the real number of Java 6 users are different for each project. If you have data about the real number of your users which are stuck to Java 6 you could do a more informed decision. Maybe release a `-java6` variant of your library and use the statistics provided by Sonatype to check the number of downloads.

I personally hope that dropping support for Java 6 will become more mainstream so I can do it as well. For example Spring 5 which is due this summer does only support Java 8+.

**Comment by eamonnmcmanus** [comment]
People who are stuck on Java 6 can use AutoValue 1.4 for as long as they like. The only issue for them is that they won't get new features and bug fixes. I don't think we can justify the effort of supporting Java 6 past 1.4.

**Comment by kevinb9n** [comment]
Agreed. I feel like a project that's okay with staying pinned to JDK 6 can probably be okay with staying pinned to AutoValue 1.4 as well.

**Comment by felixbarny** [comment]
Sounds reasonable

**Comment by adriancole** [comment]
fine with me too. we just need to make some comments in build config so ppl
don't accidentally break thing
