### ISSUE TITLE
Why do nested builders need to be NonNull?

### ISSUE THREAD

**Issue by ZacSweers** [google/auto#454]
Per this - https://github.com/google/auto/pull/442

> Treat property builders for nested @AutoValue types more like property builders for collections. If we have `ImmutableList<String> strings()` and `ImmutableList.Builder<String> stringsBuilder()`, then the list starts off empty. If you never add anything to it, the final result is an empty list. Likewise, if we have `NestedAutoValueType foo()` and `NestedAutoValueType.Builder fooBuilder()`, then `foo` starts off with its default value. If you never set anything in fooBuilder(), the final result is a default NestedAutoValueType. We only construct that default value lazily, so if you do in fact set something on the builder then the default instance of NestdAutoValueType is never constructed.

I don't really follow the reasoning here. Wouldn't it be feasible to just leave it as null if the following conditions hold?
- `foo()` has not been called
- `fooBuilder()` has not been called

In the event of the above, at build-time there would be no builder started, and one could assume null there. Otherwise this basically removed a lot of the value of nested builders for us, as most of our properties are nullable.

**Comment by eamonnmcmanus** [comment]
Don't you think it is weird for the value of `foo()` in the built object to be different depending on whether `fooBuilder()` was ever called? Even if no methods were called on the `fooBuilder()` object? What about when `foo()` is an `ImmutableList<String>` or whatever?

**Comment by hzsweers** [comment]
I think it's a decision the consumer makes. If you set the value with `foo()` and then did something later with `fooBuilder()`, it would presumably get replaced with whatever we did with `fooBuilder()`. Similarly with the reverse of that. It doesn't seem that much different than if you just re-called `foo()` with different values for some reason later. We give the option of `foo()` and `fooBuilder()` depending on their needs. Collections are an odd case, and I don't know what the correct answer is there. I do think that's likely the minority/special case though (it definitely is for us), and it seems harsh to force all builders to behave as if they're additive collections.

**Comment by eamonnmcmanus** [comment]
I'm a little unclear on the details of what you're saying. Are you talking about when we have both `Nested.Builder fooBuilder()` and `Builder setFoo(Nested x)`? In that case we have to be a bit careful: we don't allow calling `setFoo` if `fooBuilder` has already been called, because we don't want code to have a `Nested.Builder` where you can call methods but they won't have any effect.

I think the question of `@Nullable Nested foo()` is mostly independent of this. We *could* say that the default value is null, and null is allowed in `setFoo`, while also saying that if `foo()` is *not* `@Nullable` then the default value is `fooBuilder().build()`. And we *could* continue to outlaw `@Nullable` for immutable collection builders. It still bothers me that the end result would be different depending on whether `fooBuilder()` had ever been called, though.

**Comment by hzsweers** [comment]
> Are you talking about when we have both Nested.Builder fooBuilder() and Builder setFoo(Nested x)?

Yeah. My main point was just that we enjoyed having the ability to do the same for nullable types with the same rule mentioned in the next bit - `we don't allow calling setFoo if fooBuilder has already been called`

>  while also saying that if foo() is not @Nullable then the default value is fooBuilder().build()

I actually don't know that I agree with this part. Seems like it could easily be a footgun since it's not obvious. This would also break down for collections IMO, as there's a very big distinction between an empty collection and a null collection, would could lead to unexpected behavioral errors down the line. In our case, we actually generate autovalue representations of thrift structs, where nullability mirrors the requiredness of a particular field. We could default to empty collections instead of null, but then it becomes a bit of a tribal knowledge thing that *certain* collections behave differently.

> It still bothers me that the end result would be different depending on whether fooBuilder() had ever been called, though.

I don't think this changes when you make it nonnull properties only though, since you still have the hard exception for trying to call the `setFoo` method it after starting a builder.

I think simplifying would be the most flexible to users. The current API seems to take a few too many opinions on how collections and buildable types work, when it could be simplified to support any "buildable" type with the same set-after-builder rule, with maybe special handling for collections to cover the `toBuilder()` case. Since there's special handling for Guava classes anyway, I think there's enough precedent for that to be ok though.
