### ISSUE TITLE
Memoized does not work when applied to methods in the superclass

### ISSUE THREAD

**Issue by ansman** [google/auto#466]
This illustrates the problem:
```java
public abstract class Foo {
    public abstract String name();

    @Memoized
    public String hello() {
        return "Hello " + name();
    }
}

@AutoValue
public abstract class Bar extends Foo {}
```

I would expect `hello` to be memoized in `Bar` but it isn't.

**Comment by eamonnmcmanus** [comment]
`@Memoized` has [source retention](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.4.2) which means that it is not in general possible to do this. (It could work, but only if `Foo` were being compiled at the same time as `Bar`.) We could change this, but I'm not sure we would want to. Being memoized is a property that comes from the `@AutoValue` class. If you had another subclass of `Foo` that was not an `@AutoValue` then the `hello()` method would not be memoized, despite the annotation saying it was.

This does work:
```java
public abstract class Foo {
    public abstract String name();

    public String hello() {
        return "Hello " + name();
    }
}

@AutoValue
public abstract class Bar extends Foo {
  @Override
  @Memoized
  public String hello() {
    return super.hello();
  }
}
```

I think it is a clearer reflection of what you mean.

(@netdpb for a second opinion.)

**Comment by ansman** [comment]
I'm fine with it not working when compiling at different times, I'm mostly doing this to avoid code duplication.

**Comment by netdpb** [comment]
I agree with @eamonnmcmanus: `@Memoized` is only valid within an `@AutoValue`-annotated type. We should add validation so that if you apply it outside of such a type you get an immediate error instead of being surprised by the behavior.

**Comment by netdpb** [comment]
Filed #467 to track adding validation.

**Comment by ronshapiro** [comment]
I think we should allow this. I just discussed this with @netdpb and here's what we discussed (note that he's on the other side though).

If you define a `@Memoized` property in a subtype that is used in later `@AutoValue`s, but also some hand-written subclasses, there is no enforcement that the handwritten classes actually memoize the property. I think this is isn't that big of a concern, partially because `@Memoized` is simply a performance directive, not a correctness one. The practice of mixing some hand-written subtypes and some `@AutoValue` subtypes seems bizarre to me anyway.

I think this is more of a style question, and some authors and reviewers might prefer using it and others might prefer to define it on the concrete property itself, but `MemoizedExtension` doesn't need to pick a side. I think it's clear for us to define how we look up whether to memoize a value: if the most recent superclass which defines this method annotates it with `@Memoized`, then memoize, otherwise don't. 

Consider also the following case (augmented from the initial comment), which though we don't recommend, we don't currently block: 
```java
@AutoValue // <--- both types are auto values!
public abstract class Foo {
    public abstract String name();

    @Memoized
    public String hello() {
        return "Hello " + name();
    }
}

@AutoValue
public abstract class Bar extends Foo {}
```

If we didn't treat `@Memoized` as inherited across types, then it *would* be memoized in AutoValue_Foo, *not memoized* in AutoValue_Bar, but no error would be printed.

**Comment by eamonnmcmanus** [comment]
We *do* block one `@AutoValue` class from extending another, because of the well-known problems with `equals` in cases like these.

I'm not sure we can say that `@Memoized` is "simply a performance directive". If you add that to a method, you are saying that you only expect that method to be called once. That might not only be a question of performance.

**Comment by netdpb** [comment]
I think allowing `@Memoized` on a non-`@AutoValue` base class is surprising.

I think `@AutoValue` classes are intended not to be subclassed except by classes generated by AutoValue, and in that context we know what `@Memoized` on an `@AutoValue`-class's method means. `@Memoized` on another class's method, if we allow it, means only that the method will be memoized on instances of _some_ subtype of this class. There's nothing that makes any other subclass do any memoization.

That's why I think we should just disallow it unless on a method of an `@AutoValue` class.

**Comment by jbduncan** [comment]
@eamonnmcmanus

> If you add` @Memoized` to a method, you are saying that you only expect that method to be called once.

Oh, really?

I might understand if you said the method was just lazy, but when it goes beyond just that and it's also memoized? :thinking: 

I'd expect in such cases that it purposely memoizes (that is, caches its result in a lazy way) _because_ it's expensive to call it more than once normally, and people want to call it more than once without incurring too much of a speed cost.

Have I misunderstood what you're trying to explain?

**Comment by eamonnmcmanus** [comment]
@jbduncan I think indeed that I wasn't clear. What I meant is that the exact method that is marked `@Memoized` is only called once. One might *think* from looking at user code that it is called any number of times, but every call after the first ends up being handled by the generated override without calling the overridden `@Memoized` method.

**Comment by jbduncan** [comment]
Oh I see! Thanks for clearing up my misunderstanding.
