### ISSUE TITLE
Why are auto-factory releases still marked beta?

### ISSUE THREAD

**Issue by mfarrugi** [google/auto#489]
There doesn't seem to be any mention of it in the docs, and even new recent tags have still been marked as beta.

**Comment by ronshapiro** [comment]
The actual tag isn't so meaningful. Many companies, including Google, use AutoFactory in production. It's similar to how auto-common is still in 0.x releases, even though it's used in many projects. The point of both of them is that the API still isn't something that we've committed to, at least in the major-version sense of support.

We don't spend a whole lot of time on AutoFactory so I periodically will make another beta release so that users can get new features and bug fixes. At some point we decided to do -betaN releases instead of 0.x. I'm not sure how that decision was made, or whether it was deliberate. But it doesn't seem to make sense to me to go backwards at this point.
