### ISSUE TITLE
Combination of Optional and Immutable collection not supported

### ISSUE THREAD

**Issue by pettermahlen** [google/auto#498]
I'm trying to create a class similar to:

```java
@AutoValue
abstract class Foo {
  abstract Optional<ImmutableList<String>> strings();

  @AutoValue.Builder
  abstract static class Builder {
    abstract Builder strings(List<String> strings);

    abstract Foo build();
  }
}
``` 

This fails, because the generated code simply does an `Optional.of(strings)` rather than `Optional.of(ImmutableList.copyOf(Strings))`.

Based on the documentation and how things work for mandatory immutable collection parameters, I would have guessed that the nested case would be supported. Trying to get around it, I cannot quite use this trick:

```java
   abstract Builder stringsAuto(ImmutableList<String> strings);
   public Builder strings(Iterable<String> strings) {
     return stringsAuto(ImmutableList.copyOf(strings));
   }
```

as the abstract method has to use the `strings` name. That leaves method overloading, which feels a little shaky but is maybe safe?

**Comment by eamonnmcmanus** [comment]
I'm always a little skeptical when I see `@Nullable List` or `Optional<List>` because often there's no real difference between a missing list and an empty list. However, if AutoValue is generating code that doesn't compile that's clearly a bug. Meanwhile, yes, method overloading is the way to go here:

```java
   abstract Builder strings(ImmutableList<String> strings);
   public Builder strings(Iterable<String> strings) {
     return strings(ImmutableList.copyOf(strings));
   }
```

**Comment by pettermahlen** [comment]
The use case in question is a state machine (or a framework for representing such state machines), where different payloads are applicable to different states. So in this case, information that isn't applicable to a particular state should be missing, and an empty list has some sort of meaning (data is applicable/available, but empty).

I think I will move away from this model eventually, but I'm in early exploration and I want to explore other things first. But I agree the model is a little suspicious though perhaps not completely insane. :)

**Comment by eamonnmcmanus** [comment]
The improved type logic in 1.6.4 means that AutoValue no longer generates code that doesn't compile for this example, so I'm closing this. We allow you to set an `ImmutableList<Foo>` with a `List<Foo>`, and we allow you to set an `Optional<Bar>` with a `Bar`, but we don't combine the two to allow you to set an `Optional<ImmutableList<Baz>>` with a `List<Baz>`.

**Comment by feinstein** [comment]
@eamonnmcmanus why not combine the 2 once `Optional<ImmutableList<Baz>>` is accepted and this can ease things up?

**Comment by eamonnmcmanus** [comment]
@feinstein I'm not sure what you mean.

**Comment by feinstein** [comment]
I discovered this Issue once I tried to use Autovalue to generate code that would use `Optimal<ImmutbleSet<String>>` and create it with `setStrings(Set<String> strings)` and it didn't work.

As your last comment here before closing, you decided not to `combine the two to allow you to set an Optional<ImmutableList<Baz>> with a List<Baz>`.

So I was asking the reasoning behind that decision.

**Comment by eamonnmcmanus** [comment]
The cases where AutoValue allows you to set a property of type `T` with a parameter that is not exactly `T` all involve exactly one transformation. You can set an `Optional<String>` with a `String` via `Optional.of`. You can set an `ImmutableList<String>` with a `List<String>` via `ImmutableList.copyOf`. But setting an `Optional<ImmutableSet<String>>` from a `Set<String>` would require two transformations, `Optional.of(ImmutableSet.copyOf(set))`. I am concerned that if we start doing that it will become unclear exactly what does and does not work. The rule of just one transformation is simple, and is like the rule for boxing in Java. (You can assign an `int` to a `long` and you can assign a `long` to a `Long` but you can't assign an `int` to a `Long`.) The simple workaround is to make the desired transformation explicit, as I described earlier:
```java
@AutoValue
abstract class Foo {
  abstract Optional<ImmutableSet<String>> optionalSetOfStrings();

  @AutoValue.Builder
  abstract static class Builder {
    abstract Builder setOptionalSetOfStrings(ImmutableSet<String>);
    Builder setOptionalSetOfStrings(Set<String> set) {
      return setOptionalSetOfStrings(ImmutableSet.copyOf(set));
    }
  }
```

Additionally, as I stated earlier, types like `Optional<ImmutableSet<String>>` are probably best avoided, since the distinction between `Optional.empty()` and `Optional.of(ImmutableSet.of())` may not be clear.
