### ISSUE TITLE
ErrorProne: [NarrowingCompoundAssignment] Compound assignments from long to int hide lossy casts

### ISSUE THREAD

**Issue by vanniktech** [google/auto#506]
Starting with Error Prone 2.0.20 some of the generated Auto Value code gets flagged:

```
warning: [NarrowingCompoundAssignment] Compound assignments from long to int hide lossy casts
    h ^= (this.id >>> 32) ^ this.id;
      ^
    (see http://errorprone.info/bugpattern/NarrowingCompoundAssignment)
```

`id` is defined as `abstract int id()`.

Is this really an issue or can AutoValue guarantee that this will work?

**Comment by JakeWharton** [comment]
It's not an issue for this use, but it's valid to flag it. It can be worked
around by emitting the otherwise implicit integer cast of the value.

**Comment by PhilippWendler** [comment]
Maybe one should ask Error Prone to disable this check for `hashCode` methods? This pattern is probably quite common there, and it usually won't do harm.

**Comment by JakeWharton** [comment]
The potential for harm is the same as anywhere else.

You could potentially ask for it to recognize this pattern which is itself
safe, but I still think emitting the explicit cast here is reasonable.

**Comment by JakeWharton** [comment]
FWIW AutoAnnotation emits the explicit cast. Sent a PR to update AutoValue to have the same behavior.

**Comment by eamonnmcmanus** [comment]
Yes, AutoAnnotation has to cast because it makes one big expression for the whole hashCode computation. If it had used an equivalent idiom (but with `+=` instead of `^=`) we would have seen the problem there too. We did [fix](https://github.com/google/auto/commit/4f635ccd80bcca586e6785a12f8711cc0916a004) another Error-Prone issue in AutoAnnotation's hashCode computation, to do with overflows in constant expressions.

I was a little surprised that nobody inside Google had reported this, but I guess ErrorProne's findings for generated code aren't surfaced in our usual workflows.

I vaguely remember being a bit surprised that it was legal to omit the cast here. I guess I shouldn't have given in to the temptation. :-)
