### ISSUE TITLE
AutoValue requires that shared ancestor methods be public.

### ISSUE THREAD

**Issue by wberlinic** [google/auto#544]
In issue [277](https://github.com/google/auto/issues/277) @eamonnmcmanus said:
>Having an ancestor shared between different @AutoValue classes is definitely a supported use case. We don't allow one @AutoValue class to extend another, though, for the reasons @PhilippWendler alludes to.

I would expect this to work:
```
package com.example.a;
public abstract class BaseArgs {
    protected abstract Object getFoo();
    public void useFoo() {
        getFoo().execute();
    }
}
```
```
package com.example.b;
public abstract class Args extends BaseArgs {
}
```
However, I get an error in the generated equals:
error: getFoo() has protected access in Args
```
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Args) {
      Args that = (Args) o;
      return (this.foo.equals(that.getFoo()));
    }
    return false;
  }
```
This is due to the base args being in another package and getFoo being protected. The generated auto-value object is not able to access the protected method of `that` instance.  I can workaround it by making the protected method public but I would prefer to hide the method.

As auto-value is generated all of the fields it could easily solve this by instead casting `that` to AutoValue_Args and comparing the fields.
```
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof AutoValue_Args) {
      AutoValue_Args that = (AutoValue_Args) o;
      return (this.foo.equals(that.foo));
    }
    return false;
  }
```

**Comment by eamonnmcmanus** [comment]
That's an interesting problem!

The reason that casting to `AutoValue_Args` works is that `AutoValue_Args` overrides the protected `getFoo()` method in order to implement it. That means that the reference to `getFoo()` becomes a reference to a method in the same package (actually the same class) so it is legal. But if the type is `Args` then the reference is to a protected method in another package and that doesn't work.

The reason the generated code uses `Args` rather than `AutoValue_Args` is that it should work even when comparing against another implementation of `Args`. I'm not sure how common it is for people to want to do that but technically what you propose would be a breaking change.

There is a simple, if ugly, workaround, which is to redeclare the abstract `getFoo` method in `Args`:

```java
@AutoValue
public abstract class Args extends BaseArgs {
  @Override
  protected Object getFoo();
}
```

I suppose it would be possible for AutoValue to detect this situation and fall back to using `AutoValue_Args` rather than generating code that doesn't compile. That seems kind of hacky for what seems like an unusual case. I don't believe anyone else has mentioned this over the years that AutoValue has existed.

**Comment by PhilippWendler** [comment]
As a user of AutoValue, I would prefer such a breaking change not to be made.

**Comment by eamonnmcmanus** [comment]
Yes, we're definitely not going to change the `equals` method so that it always references the `AutoValue_Foo` class. The only question is whether we might detect that there are protected methods being inherited from another class, in which case the current generated implementation is not going to compile. In that case only, we might change the `equals` implementation to reference `AutoValue_Foo`. However that seems kind of weird and, given that there is a workaround and that the problem does not seem common, I'm not inclined to make the change.

**Comment by eamonnmcmanus** [comment]
Realistically, I don't think we're going to do anything about this obscure problem. I expect that very few people will be affected by it, and those that are can apply the workaround I mentioned above.
