### ISSUE TITLE
BeanUtils getProperty not working?

### ISSUE THREAD

**Issue by wissil** [google/auto#569]
I have defined a property  `status` in my class like this:

`public abstract Optional<String> status();`

... and trying to access it via `BeanUtils` from another class like this: 

`
```
MyClass value = // ... 
System.out.println(value); // this properly prints out the object with 'status' property
String fieldValue = BeanUtils.getProperty(value, "status"); // here fails
```
`

... which causes an exception:

`Caused by: java.lang.NoSuchMethodException: Unknown property 'status' on class 'class AutoValue_MyClass'`. 

I can see that the property is generated in the AutoValue_MyClass like this:

`private final Optional<String> status;`

However, it still causes the problem. Is there any other way to access the property?

**Comment by tbroyer** [comment]
Isn't BeanUtils looking for a `getStatus` accessor?

**Comment by eamonnmcmanus** [comment]
I think @tbroyer is correct. AutoValue allows you to call the getter for the `status` property either `status()` or `getStatus()`, provided you use one or the other convention consistently for all the properties in a given `@AutoValue` class. The JavaBeans conventions require you to use the `getStatus()` form, so that's what you should do if you want to use BeanUtils.

The JavaBeans API and its documentation have always been terrible so it's not surprising that this is a source of confusion. The convention above is described [here](http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/), after you click through a pointless license to access 20-year-old documentation. I'm not sure it's described in the [`java.beans`](https://docs.oracle.com/javase/8/docs/api/java/beans/package-summary.html) online API docs.

**Comment by tbroyer** [comment]
> The convention above is described here, after you click through a pointless license to access 20-year-old documentation. I'm not sure it's described in the java.beans online API docs.

It's actually briefly touched upon in https://docs.oracle.com/javase/8/docs/api/java/beans/PropertyDescriptor.html#PropertyDescriptor-java.lang.String-java.lang.Class-

**Comment by eamonnmcmanus** [comment]
Aha, I searched for it in vain, but didn't think to look in the constructor of a secondary class. :-)
Thanks!
