### ISSUE TITLE
Rebuild and Re-Deploy AutoFactory for Java 9

### ISSUE THREAD

**Issue by sgarfinkel** [google/auto#581]
I think the version of AutoFactory available on Maven Central hasn't been built with the past few months' commits that add Java 9 support. In my experience, the current release was causing issues when building on Java 9. Would it be possible to build and deploy an updated version to Maven Central?

**Comment by sgarfinkel** [comment]
Any status update on this? Sadly it doesn't seem JitPack will work for this.

**Comment by mkgl** [comment]
+1 here; auto-factory 1.0-beta5 (btw, scm tag is missing) was released in May 2017 with:

* auto-common:0.6 (now 0.10, JDK9 support seemingly since 0.9)
* auto-value:1.1 (now 1.5.3)
* auto-service:1.0-rc2 (now 1.0-rc4)

Would be worth publishing at least a beta6 on maven central. Anyone here who can help us make it happen?

**Comment by corydolphin** [comment]
@eamonnmcmanus I see you've cut the last few releases for the project. Is it possible to get your help pushing through a release?

**Comment by ronshapiro** [comment]
Let's converge on #658. I tried to release last week and had a silly mistake, trying again now.
