### ISSUE TITLE
Can autoValue handle Cyclic reference?

### ISSUE THREAD

**Issue by liudaomanbu** [google/auto#591]
Sometimes there is cyclic reference between the beans.
For example,Teacher reference School,And School reference Teacher.
How does the autoValue deal with this situation?

**Comment by eamonnmcmanus** [comment]
Because `@AutoValue` classes are immutable, you can't have two instances (whether of the same class or of different classes) that reference each other. One of them would have to be constructed first, and then there's no way to change it after the second is constructed. Well, strictly speaking you can have something like a mutable `List` property, but we strongly recommend against that because it violates expectations and plays badly with things that depend on `hashCode()`.

But there's no reason you can't have a graph of objects where School references a Teacher instance which references a different School instance.
