### ISSUE TITLE
hashCode() won't work properly in @AutoValue generated class

### ISSUE THREAD

**Issue by Sathawale27** [google/auto#635]
hashCode() will not work properly, if there is an any type of `abstract h$();` method in @AutoValue annotated class. While generating hashCode() method, It will take h$ local parameter instead of global one.

**Comment by eamonnmcmanus** [comment]
The assumption is that the `@AutoValue` class will not have identifiers with `$` in them, since those are reserved for generated code, per the [JLS](https://docs.oracle.com/javase/specs/jls/se10/html/jls-3.html#jls-3.8).

> The dollar sign should be used only in mechanically generated source code or, rarely, to access pre-existing names on legacy systems.

We did actually use `this.$p` in earlier versions. But I think that makes the generated code harder to read. If we wanted to cover this case it is a one-line fix: just call `#hashCodeExpression(this.$p)` instead of `#hashCodeExpression($p)` in `autovalue.vm` and `autooneof.vm`.
