### ISSUE TITLE
Generated builder is not recognized

### ISSUE THREAD

**Issue by smac89** [google/auto#650]
I wrote an extension that generates a builder interface for my class's builder, but this other builder's methods are not being picked up in the builder generated by auto-value.

Example:

```java
@AutoValue
public abstract class ValueWithOptional {
    public abstract Optional<String> getValue1();
    public abstract Optional<String> getValue2();
    public abstract Optional<String> getValue3();

    public static Builder builder() {
        return new AutoValue_ValueWithOptional.Builder();
    }

    @AutoBuilder // Used to indicate builders are to be generated
    @AutoValue.Builder
    interface Builder extends AutoBuilder_ValueWithOptional<Builder> {
        Builder value1(String value1);
        Builder value2(String value2);
        Builder value3(String value3);
        ValueWithOptionalBuilder build();
    }
}
```
This is the builder that is generated:

```java
interface AutoBuilder_ValueWithOptional<B extends AutoBuilder_ValueWithOptional<B>> {
  B value1(Optional<String> value1);

  B value2(Optional<String> value2);

  B value3(Optional<String> value3);
}
```

Now when the compilation is finished, I get errors complaining that the final builder class does not implement the methods found in this new interface. It will seem to me that autovalue is eagerly taking all methods found in the builder class before the newly generated one is created.

Is there a way to fix this?

Thanks!

**Comment by eamonnmcmanus** [comment]
I'm actually a little surprised that AutoValueProcessor gets as far as generating the implementation of the `Builder` interface. But I would certainly not expect it to be able to do what you want. It would be a bug for AutoValueProcessor to invoke extensions on an `@AutoValue` class that is not yet fully defined (for example, if `ValueWithOptional` implemented an interface that is generated by another processor). I think it is also a bug for it to invoke extensions when the builder is not yet fully defined. In both cases, AutoValueProcessor should assume that the missing classes might be generated by another processor that has not run yet. So it should defer processing to the next [round](https://docs.oracle.com/javase/10/docs/api/javax/annotation/processing/Processor.html), in the hope that the other processor will generate the missing types on this round. Of course if you're expecting `AutoBuilder_ValueWithOptional` to come from an extension, and extensions aren't invoked when processing is deferred, it's not going to work.

One alternative would be to write a separate annotation processor instead of an extension. It would generate `AutoBuilder_ValueWithOptional`, and that might work. However, since it appears that AutoValueProcessor is not correctly deferring processing as described above, when the builder parent class is missing, there's a fair chance it won't work. And even if it does work, you're basically going to have do all the work that AutoValueProcessor does to determine what the properties are. So I'm not sure there's a great solution here.

I'd also add a philosophical remark. We deliberately made it so that users have to write the full API of their `@AutoValue` class and its builder. We could instead have made it so that the builder is entirely generated based on the properties, as a generalization of what you're suggesting here. It doesn't appear that we really document that publicly, which we should probably fix. Here's an excerpt from some of the Google-internal documentation that talks about the rationale:

*   Users of your API can see its API declarations in plain Java. In contrast,
    with a generated API, they must learn how to navigate to the generated code,
    or they must learn the tool's rules and configuration options.
*   The API can be as small as you want. In contrast, a generated API must
    provide the union of all features *anyone* might want, or it must support a
    custom configuration mechanism.
*   The generator can provide you a choice between mutually exclusive API
    options. For example, AutoValue lets you define `@Nullable Foo foo()` or
    `Optional<Foo> foo()` -- and you can choose whether to use the `Optional`
    from `java.util` or from `com.google.common`.
*   By omitting APIs and providing choices, the generator can not only provide a
    better API but also reduce dependencies. Consider again the example of
    `Optional`: Some projects can't use Java 8 APIs, and others can't use
    `com.google.common`.
*   The generator can permit more flexibility in API naming. For example, it
    might recognize that `addChild()` and `addChildren()` must go together,
    though it would never have chosen the word "children" on its own.
*   If API users misconfigure their IDEs, the resulting compile errors are
    localized to the class that refers to generated code, rather than appearing
    on other usages of that class.
*   Most refactorings, like moving your class, or renaming a public method with
    many callers, Just Work in the usual fashion.
*   When APIs are always hand-written, there are no barriers to *documenting*
    those APIs. This still happens in the usual way. (Sometimes these are
    "self-explanatory" methods that don't require documentation, but often they
    are not.)

**Comment by smac89** [comment]
This is interesting. I already went ahead and implemented it as a separate processor, and I still encounter the same issues. So if there is no way to make this work with just annotation processing, is it possibly going to work by manipulating the compilation process? I'm using maven, so I was thinking if it is possible to have my processor run on a different stage before the autovalue processor kicks in.

I will explore this other option.

Thanks

**Comment by smac89** [comment]
Could another option be to defer autovalue annotation processing until parent classes are defined?

As for generating the abstract methods, I don't really need as elaborate a method as employed by auto-value, so something like this works for me:

```java
private Set<ExecutableElement> getAbstractValueProperties(TypeElement autoValueClass) {
    return MoreElements.getLocalAndInheritedMethods(autoValueClass, elementUtils)
                       .stream()
                       .filter(m -> m.getModifiers()
                                     .contains(Modifier.ABSTRACT))
                       .collect(Collectors.toSet());
}
```
