### ISSUE TITLE
Use a @Generated with CLASS retention so its excluded from code coverage by default

### ISSUE THREAD

**Issue by lqc** [google/auto#661]
JaCoCo has recently added a new feature that automatically excludes classes and methods with ```@Generated``` annotation (https://github.com/jacoco/jacoco/issues/696). The only requirement is that the annotation is retained in the class file (the ```javax.annotation.Generated``` is not).

AutoValue should create its own ```@Generated``` annotation with retention scope of at least ``CLASS`` and use it instead.

**Comment by eamonnmcmanus** [comment]
I think that would be unhelpful. You should perhaps argue that `javax.annotation.processing.Generated` should have `CLASS` retention and try to convince the JDK maintainers to make that change. I don't think inventing our own `@Generated` to replace the standard ones is the right solution.

You can define your own `@Generated` with `CLASS` retention and write this:
```java
import com.example.Generated;

@AutoValue
@CopyAnnotations
@Generated
abstract class Foo {...}
```

Then the generated `AutoValue_Foo` will have both the standard (source-retention) `@Generated` and your custom one.

**Comment by lqc** [comment]
I agree that it would be best to change retention of JDK's annotation, but I highly doubt it will happen. FWIW, a few other projects like Immutables and Lombok already added their annotations to address this.

Either way, thanks for pointing out a nice workaround. It's a bit of boilerplate to write on every class. Have you considered adding some support for meta-annotations, e.g.:

``
@AutoValue
@AutoValue.CopyAnnotations
@Generated

**Comment by eamonnmcmanus** [comment]
I still think defining a custom `@Generated` is confusing. It's overloading the meaning of the annotation. Other annotation processors can potentially inspect the output of (e.g.) Immutables looking for the standard `@Generated` annotations and they will be misled if they don't also have the logic to accept `@Generated` from any package. I personally think this change to JaCoCo is wrong. Being generated code and being excluded from coverage analysis are two different things that should not be shoehorned into the same annotation. JaCoCo has mechanisms for filtering out code from analysis and it would make more sense to define a filter that excludes classes matching the RE `.*\.\$*AutoValue_.*`, i.e. all classes whose simple names start with `AutoValue_` possibly preceded by one or more `$` signs.

The idea of meta-annotations is interesting. The main concern I would see is that the AutoValue processor would have to run for every single class being compiled, and not just classes that have the `@AutoValue` annotation, so that could make compilation a bit slower.
