### ISSUE TITLE
Using a collection builder with ImmutableSortedSet

### ISSUE THREAD

**Issue by jonfreedman** [google/auto#666]
I want to have a class similar to the below but ImmutableSortedSet.Builder throws an exception from it's factory method.  Is this possible?

    public abstract static class Builder {
        private static Builder builder() {
            return new AutoValue_Object.Builder();
        }

        abstract ImmutableSortedSet.Builder<ComparableObject> pointsBuilder();

        public abstract Builder setPoints(final ImmutableList<ComparableObject> points);

        public Builder addPoint(final ComparableObject point) {
            pointsBuilder().add(point);
            return this;
        }
        
        public abstract Object build();
    }

**Comment by jonfreedman** [comment]
I had a quick look into what's going on, I would say that [ImmutableSortedSetDeserializer](https://github.com/FasterXML/jackson-datatypes-collections/blob/master/guava/src/main/java/com/fasterxml/jackson/datatype/guava/deser/ImmutableSortedSetDeserializer.java) in jackson-datatype-guava sets president for using `ImmutableSortedSet.naturalOrder()` instead of `ImmutableSortedSet.builder()`

**Comment by eamonnmcmanus** [comment]
It's a fair point. `ImmutableSortedSet.builder()` throws `UnsupportedOperationException` because its signature would ideally be the same as `ImmutableSortedSet.naturalOrder()`, i.e. `static <E extends Comparable<?>> Builder<E> builder()`. But that's not possible because it conflicts with the signature in the ancestor class `ImmutableSet`, which is `static <E> Builder<E> builder()`. I think throwing an exception is kind of obnoxious but that's how it is (and has been since 2009).

We could recognize `naturalOrder()` for `ImmutableSortedSet` and `ImmutableSortedMap`. If the element type is not actually `Comparable` then this would provoke a surprising error in the generated code, unless AutoValue makes the `Comparable` check itself.

**Comment by jonfreedman** [comment]
I think the alternative would involve being able to define the factory method somehow with an annotation?
