### ISSUE TITLE
raw types warning in AutoAnnotation generated class, when source class suppresses it

### ISSUE THREAD

**Issue by dpursehouse** [google/auto#725]
In the gerrit project we have [OptionUtil](https://gerrit.googlesource.com/gerrit/+/refs/heads/master/java/com/google/gerrit/util/cli/OptionUtil.java) which has an `@AutoAnnotation` annotated method that takes a parameter `Class<? extends OptionHandler> handler`.

This generates a warning in Eclipse because `OptionHandler` is a raw type and the generic reference must be parameterized. This warning is suppressed with `@SuppressWarnings("rawtypes")`.

The generated `AutoAnnotation_OptionUtil_newOption` class, however, does not get the suppression, and thus causes a warning.

Is there any way to make `AutoAnnotation` carry over the `SuppressWarnings` annotation?

Note: we can't change the declaration because the type is from a third party library, and doing so causes compilation errors in other parts of the code that reference it.

**Comment by nglorioso** [comment]
Hi there! I tried reproducing the warning in IntelliJ (my local setup) by removing the `@SuppressWarnings("rawtypes")`, and I didn't get a rawtypes warning for `Class<? extends OptionHandler>` as a local variable, parameter, etc.

Can you send a screenshot of your Eclipse instance where you're seeing the rawtypes issue (ideally when you've removed the `@SuppressWarnings("rawtypes")`? Are you looking inside the generated code?

**Comment by dpursehouse** [comment]
Here's the warning in the code after commenting out the `@SuppressWarnings`:

<img width="670" alt="Screen Shot 2019-04-20 at 13 03 28" src="https://user-images.githubusercontent.com/836426/56452597-5464fb80-636d-11e9-8f8c-782fe4c0bcd3.png">

And the warning in the generated code:

<img width="662" alt="Screen Shot 2019-04-20 at 13 03 56" src="https://user-images.githubusercontent.com/836426/56452598-5464fb80-636d-11e9-9fd4-5db4ba363286.png">

**Comment by dpursehouse** [comment]
I've been able to solve this by setting the "Ignore optional compile problems" to "yes" in the Java Build Path settings for the `.apt_generated` folder, so I guess this issue can be closed.

<img width="689" alt="Screen Shot 2019-04-20 at 13 09 30" src="https://user-images.githubusercontent.com/836426/56452619-c63d4500-636d-11e9-8a7c-20cda0aebe70.png">

**Comment by eamonnmcmanus** [comment]
Looking at this more closely, perhaps we can improve the experience here. Here's the relevant member of the `Option` annotation:

```java
    Class<? extends OptionHandler> handler() default OptionHandler.class;
```

This *can't* be declared as `Class<? extends OptionHandler<?>>` because then the default value (of type `Class<OptionHandler>`) wouldn't be assignable to it. In practice it's generally a bad idea for annotation members to be generic classes because it means the consumer of the annotation is going to have to conjure up a type parameter out of nowhere. But given that it's a thing people do, perhaps we should detect this case and emit appropriate `@SuppressWarnings` annotations in the generated code.

Incidentally, in the code at hand I would suggest moving the `@SuppressWarnings` in `OptionUtil` onto just the parameter it applies to, rather than the whole method. Alternatively you could declare the parameter as `Class<? extends OptionHandler<?>> handler`, which AutoAnnotation will accept. Then you could have a cast with `@SuppressWarnings` at the call site:
```java
    @SuppressWarnings("unchecked")
    Class<? extends OptionHandler<?>> handler = (Class<? extends OptionHandler<?>>) o.handler();
    return OptionUtil.newOption(
        prefix + o.name(),
        aliases,
        o.usage(),
        o.metaVar(),
        o.required(),
        false,
        o.hidden(),
        handler,
        o.depends(),
        new String[0]);
```

**Comment by eamonnmcmanus** [comment]
Incidentally it's still the case that the args4j code could be improved. Instead of this:

```java
    Class<? extends OptionHandler> handler() default OptionHandler.class;
```

it could have this:

```java
    Class<? extends OptionHandler> handler() default DefaultOptionHandler.class;
```

where `public abstract class DefaultOptionHandler extends OptionHandler<Object>` is a class explicitly defined to be the default value. That would be cleaner than repurposing  `OptionHandler` for the job. Possibly it could be a concrete class too, instead of having `if (c == OptionHandler.class)` checks in args4j.

**Comment by cushon** [comment]
`Class<? extends OptionHandler>` probably shouldn't result in a rawtypes warning: [JDK-6885255](https://bugs.openjdk.java.net/browse/JDK-6885255), [JDK-8134009](https://bugs.openjdk.java.net/browse/JDK-8134009). It's is arguably a bug in Eclipse that it produced those warnings.

**Comment by eamonnmcmanus** [comment]
Realistically, I think we're not going to do anything here. The problem is ultimately due to a poorly-designed annotation definition, and there are workarounds that have been detailed in earlier comments.
