### ISSUE TITLE
Generated Builder class has 'unnecessarily nested else clause' warning

### ISSUE THREAD

**Issue by dpursehouse** [google/auto#731]
A builder defined as:
 
```
@AutoValue.Builder
  public abstract static class Builder {
    public abstract Builder id(Id id);

    public abstract Id id();

    public abstract Builder commitId(ObjectId commitId);

    public abstract Optional<ObjectId> commitId();

    <snip>
```

Generates the `commitId()` method:

```
    @Override
    public Optional<ObjectId> commitId() {
      if (commitId == null) {
        return Optional.empty();
      } else {
        return Optional.of(commitId);
      }
    }
```

This causes a warning at the else clause.  If possible it would be better to generate code like:

```
    @Override
    public Optional<ObjectId> commitId() {
      if (commitId == null) {
        return Optional.empty();
      }
      return Optional.of(commitId);
    }
```

(Note the warning can be suppressed in Eclipse by disabling optional warnings for generated code, but still...)

**Comment by tbroyer** [comment]
Or
```java
return Optional.ofNullable(commitId);
```

**Comment by eamonnmcmanus** [comment]
Causes a warning from what? It seems like a controversial kind of warning to me. From internal discussions on Google's Java mailing lists, it's clear that opinions are sharply divided as to whether code like the code in question is good or bad. Since I wrote the template that it is generated from, you can guess which side of the argument I am on. :-)

Having said that, @tbroyer's suggestion is an excellent way to sidestep the question.

**Comment by eamonnmcmanus** [comment]
Having looked into it further, the reason the code doesn't already use `.ofNullable` is that that isn't available for `OptionalInt` etc. I also considered switching to `?:`, but that doesn't work either because (at least in Java 8) type inference isn't good enough to figure out the appropriate type for `Optional.empty()`, so you get this:
```
incompatible types: Optional<? extends Object> cannot be converted to Optional<String>
        ? Optional.empty()
        ^
```

I'd suggest disabling this misguided warning, or (as @dpursehouse mentioned) turning off all warnings for generated code.

**Comment by dpursehouse** [comment]
> Causes a warning from what?

Sorry for not being clear.  It's in Eclipse.

I've edited the title.
