### ISSUE TITLE
AutoValue actually depends on Java 8+

### ISSUE THREAD

**Issue by chingor13** [google/auto#771]
The auto-value documentation claims that it support Java 1.6+, but due to its transitive dependencies, it actually requires Java 8.

auto-value 1.6.6 depends on auto-service 1.0-rc6. auto-service uses guava's `com.google.common.collect.ImmutableSet.toImmutableSet()` which is only available in the `-jre` flavor of guava (which requires Java 8+).

**Comment by eamonnmcmanus** [comment]
The AutoValue processor requires at least Java 8 to run. It generates code that can compile on Java 6. This means that you can do `javac -source 6 -target 6 Foo.java` and it will work even if `Foo.java` uses `@AutoValue`,. But your `javac` must be at least Java 8.

We could probably document this better, making a clearer distinction between the version needed for the compiler and the version of the target code. Also, while I believe we do still generate code that is compatible with Java 6, we only test compatibility with Java 7, so we can expect that Java 6 compatibility will stop working at some point, if it hasn't already.

**Comment by elharo** [comment]
https://github.com/google/auto/issues/773 is related

The fix is probably to stop recommending users add autovalue to their own dependencies instead of the annotation processor path. 

Important: autovalue and autovalue-annotations are not the same thing. The latter does need to be in dependencies, but is not the artifact at issue here.
