### ISSUE TITLE
Documentation should prefer specifying annotation processor paths

### ISSUE THREAD

**Issue by netdpb** [google/auto#773]
https://github.com/google/auto/blob/master/value/userguide/index.md#in-pomxml first suggests to use `<provided>true</provided>` on the Maven dependency, and then suggests configuring `<annotationProcessorPaths>` as an alternative.

We should switch the priority of those (for all artifacts). Using `<provided>true</provided>` puts the annotation processor and its dependencies on the compile-time and runtime classpath, and could lead to linkage errors at runtime (e.g., https://github.com/googleapis/java-core/issues/46).

**Comment by cpovirk** [comment]
Coincidentally, I [updated the AutoService docs in this way](https://github.com/google/auto/commit/7b0ce2dbed242dc55d2916db24cc2ac8761578e4#diff-8c9513528e170b62556353ac79283c4fR47) just a few days ago. My immediate motivation there was an additional advantage of using the annotation-processor path: As soon as you set one annotation-processor path in your project (for example, [for Error Prone](https://errorprone.info/docs/installation#maven), even though that's a plugin rather than a true(?) annotation processor), javac requires you to do them all that way. (It's also nice to be able to avoid `optional`/`provided` for the annotations artifact, at which point you're stuck adding separate entries for the annotations and the processor, so you might as well do it "right" :))

**Comment by netdpb** [comment]
Can we just do the same thing for all the auto* projects?

**Comment by cpovirk** [comment]
I think we should. I'm not sure that AutoFactory has separate annotation and processor artifacts yet, so that would be step 1 for it.

**Comment by netdpb** [comment]
OK, so this issue can cover that whole effort.

**Comment by cpovirk** [comment]
Also, filed https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/986 to see if it's worth recommending this pattern in our best practices.
