### ISSUE TITLE
Provide a no-dependency way to accumulate for collections

### ISSUE THREAD

**Issue by ogregoire** [google/auto#794]
The recommended way to [accumulate items into an immutable collection](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#-accumulate-values-for-a-collection-valued-property-without-breaking-the-chain) shows examples using Guava.

Some libraries use AutoValue but don't want to force the user to use Guava because Guava is known to cause headaches when different libraries require/provide different versions of Guava.

So it would be nice to have collection builders present directly in AutoValue, like a ListBuilder, a SetBuilder, a MapBuilder. Those builders would then return Collection.unmodifiable***-wrapped collections.

**Comment by tbroyer** [comment]
> Some libraries use AutoValue but don't want to force the user to use Guava because Guava is known to cause headaches when different libraries require/provide different versions of Guava.

This is no longer the case since Guava 21.0, released nearly three years ago: https://groups.google.com/d/topic/guava-announce/6mtQTDDADsg/discussion

> So it would be nice to have collection builders present directly in AutoValue, like a ListBuilder, a SetBuilder, a MapBuilder. Those builders would then return Collection.unmodifiable***-wrapped collections.

This would make auto-value a runtime dependency, which is currently not the case (see https://github.com/google/auto/blob/28a2c791575a7e4545293169bea0921b81363a3d/value/userguide/why.md)

**Comment by ogregoire** [comment]
> This is no longer the case since Guava 21.0, released nearly three years ago: https://groups.google.com/d/topic/guava-announce/6mtQTDDADsg/discussion

The Guava team having taken measures against that issue doesn't mean it's the end of it, as seen by the number of Stack Overflow questions asked and the number of issues on the Guava issue tracker.

Also, even if it's Guava, libraries shouldn't depend on other libraries.

> This would make auto-value a runtime dependency, which is currently not the case (see https://github.com/google/auto/blob/28a2c791575a7e4545293169bea0921b81363a3d/value/userguide/why.md)

AutoValue generates Java files. Those builders could be integrated as part of the generated classes. Or it could detect that we have an abstract add method and generate the accumulator code for us.

**Comment by eamonnmcmanus** [comment]
AutoValue actually has nearly everything you need to roll this yourself. If you define this...

```java
public class ListBuilder<E> extends ArrayList<E> {
  public List<E> build() {
    return Collections.unmodifiableList(this);
  }
}
```

...then you can write this...

```java
@AutoValue
public abstract class Foo {
  public abstract List<String> strings();

  public static Builder builder() {
    return new AutoValue_Foo.Builder();
  }

  @AutoValue.Builder
  public abstract static class Builder {
    public abstract ListBuilder<String> stringsBuilder();
    public abstract Foo build();
  }
}
```

...and then use `stringsBuilder()` as described in the [documentation](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#accumulate).

The only hole is that it will fail if you add a `toBuilder()` method to `Foo` because AutoValue doesn't know how to create a `ListBuilder` from a `List`. This works for `ImmutableList.Builder` because AutoValue has [special-case logic](https://github.com/google/auto/blob/0a7c049f5c652ea81a7573f689143706fe1c4adb/value/src/main/java/com/google/auto/value/processor/PropertyBuilderClassifier.java#L292) to create an empty `ImmutableList.Builder` and then call `addAll` on it. We could conceivably generalise that logic.

Having said all that, I'm not sure that there are strong enough reasons for avoiding the Guava collections to justify such a change. Explicitly-immutable collections are a very good fit for the immutable value types that AutoValue defines.

**Comment by ogregoire** [comment]
> Having said all that, I'm not sure that there are strong enough reasons for avoiding the Guava collections to justify such a change. Explicitly-immutable collections are a very good fit for the immutable value types that AutoValue defines.

I want to avoid the Guava collections because once burned, twice shy. I will never write a library that provides public API related even by far to Guava. I've been through the dependency hell and I don't want to force it upon my users. If I use Guava, the final user will never know it: it'll be shaded and hidden.

I understand the arguments behind an explicit `ImmutableList`, and I agree with it in a perfect world. I however don't agree with the fact that any single immutable list should be a Guava `ImmutableList`. If I use `List.of("One", "Two", "Three")`, it's good, and I don't need it to be named `ImmutableList`. In my view, if a Guava features makes it into the JDK, I will use the JDK version all the time. I don't use Guava's `Optional`, I use the JDK's `Optional`; I don't use Guava's `Function`, I use the JDK's `Function`; I don't use Guava's `FluentIterable`, I use the JDK `Stream`. I will use Guava over any other library if I require `Range`, `Multiset`, `BiMap`, `ByteSource` or `Strings`. But when I don't *need* a Guava feature, I will not add it just to have my `List` be typed `ImmutableList`. That's not a feature: that's sugar.

In several libraries I just don't need Guava. I however need `AutoValue` and a `ListBuilder` and it pains me to have to write it in every single library because my golden rule is "no API dependencies" (which at some point in time was also Guava's motto, but that's another topic), but I'll copy those `ListBuilder`, `MapBuilder` and friends until you finish the collection building feature (yes, I personally see it unfinished as long as this issue isn't addressed).

Finally, the code you wrote is buggy. Could you fix it? If anyone copies it, the following bug can happen:

    Foo.Builder fooBuilder = Foo.builder();
    builder.stringsBuilder().add("One");
    builder.stringsBuilder().add("Two");
    Foo foo = fooBuilder.build();
    builder.stringsBuilder().add("Three");
    Foo foo2 = fooBuilder.build();
    assertThat(foo).isNotEqualsTo(foo2); // fails

**Comment by tbroyer** [comment]
Fwiw, you may want to have a look at https://immutables.org

**Comment by ogregoire** [comment]
> Fwiw, you may want to have a look at https://immutables.org

That's an excellent alternative. Thank you! It does all I need and a bit more.

**Comment by eamonnmcmanus** [comment]
> Finally, the code you wrote is buggy.

Yes, the `List.copyOf` introduced in Java 10 provides a much better alternative to the tedious `Collections.unmodifiedList(new ArrayList<>(this))` that I didn't want to write. :-)

We don't current plan to introduce a runtime API for AutoValue, which is where we might otherwise put `ListBuilder` etc. If there's another reason to do so then we might revisit that, but I don't think Guava-allergy is a good enough reason on its own. On the other hand, I think it's fairly likely that we'll allow the `addAll`/`putAll` logic to apply to any class with those methods, rather than just the Guava `Immutable*.Builder` ones, so that the trivial roll-your-own-builder described above will work properly.

**Comment by octylFractal** [comment]
I would like to request the ability to provide custom `toBuilder()` support logic. I'm using FastUtil for memory/CPU purposes, and that means I can't use the Guava-equivalent collections as they would box primitives. I'm fine with writing a custom builder class for them, but I would like to be able to add e.g. `static IntListBuilder from(IntList)`.

**Comment by eamonnmcmanus** [comment]
@octylFractal can you explain in a bit more detail what you have in mind? Perhaps with an example of the code you would like to be able to write but currently cannot. There's no `IntListBuilder` in FastUtil as far as I can see, so this is a bit unclear to me.

**Comment by octylFractal** [comment]
I was referring to your previous comment https://github.com/google/auto/issues/794#issuecomment-559870938, where you said "We could conceivably generalise that logic.". `IntListBuilder` would be a custom class that I write for FastUtil's `IntList`, and that would work except for the fact that I can't use `toBuilder()` since there's no way to define it on `IntList`. I want to be able to add something that tells AutoValue how to construct my custom `IntListBuilder` from an `IntList`.

**Comment by eamonnmcmanus** [comment]
I see. One thing we could do would be to generalize [this logic](https://github.com/google/auto/blob/b0bf15e19f2b8a794a7890201330d774d9948f12/value/src/main/java/com/google/auto/value/processor/PropertyBuilderClassifier.java#L290). Currently it looks to see whether the type is a Guava collection builder such as `ImmutableList.Builder`, and if so whether it has a method called `addAll` or `putAll`. In that case we know that we'll be able to call that method on a new instance of the builder in order to copy an existing built collection (an `ImmutableList` etc) into it. We also know that the parameter type of the `addAll` or `putAll` method will be correct, because we know the Guava API.

We could remove the check for Guava collection builders specifically, and instead check not only that there is a method `addAll` or `putAll` but also that it has a single parameter and that that parameter is assignable from the built collection type. That would be cleaner than what we do today, though possibly a little tricky to implement. So then if you put an `addAll` method in your `IntListBuilder` we would call it, the same as we do today for an `ImmutableList.Builder`.

**Comment by eamonnmcmanus** [comment]
Release 1.7.1 now has the generalized logic mentioned [above](https://github.com/google/auto/issues/794#issuecomment-619293298).
