### ISSUE TITLE
Issue with JSR-303 annotations (javax validation): annotations copied on fields and methods causing double validation

### ISSUE THREAD

**Issue by benjaminlefevre** [google/auto#808]
Hi guys,

I try to use AutoValue and Java validation (jsr-303) in same time.

It works, but I have an issue with annotations. 

They are reported twice in the generated class: on the generated field and on the getter method, causing double validation (and generating double violation messages, when a validation fails).

Example with the @NotBlank annotation:

```
@AutoValue
public abstract class Test {
  @NotBlank
 public abstract String name();
}
```

Generated code:

```

@Generated("com.google.auto.value.processor.AutoValueProcessor")
final class AutoValue_Test extends Test {

  private final @NotBlank String name;

  AutoValue_Test(
      @NotBlank String name) {
    if (name == null) {
      throw new NullPointerException("Null name");
    }
    this.name = name;
  }

  @Override
  public @NotBlank String name() {
    return name;
  }

  @Override
  public String toString() {
    return "Test{"
         + "name=" + name
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Test) {
      Test that = (Test) o;
      return this.name.equals(that.name());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= name.hashCode();
    return h$;
  }

```

Is there a way to tell AutoValue to only copy an annotation on field or method? if not, could it be implemented in a near future?

Thank you.

**Comment by eamonnmcmanus** [comment]
If the annotation is a type annotation (has a [`Target`](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Target.html) that includes [`TYPE_USE`](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/ElementType.html#TYPE_USE)) then AutoValue considers that it is part of the type, and will include it everywhere the type appears. This is the case for `@NotBlank` in `javax.validation` 2.0.1. The only control we provide is that you can use [`@CopyAnnotations`](https://www.javadoc.io/doc/com.google.auto.value/auto-value/latest/com/google/auto/value/AutoValue.CopyAnnotations.html) with an `exclude` so that `@NotBlank` is not copied anywhere. But we don't provide a way to copy it only in some places but not others.

Having said all that, I just did the experiment with Hibernate Validator 6.1.1 and I only see one `ConstraintViolation`:

```
    ValidatorFactory validatorFactory = Validation.buildDefaultValidatorFactory();
    Validator validator = validatorFactory.getValidator();
    Test test = Test.create("");
    Set<ConstraintViolation<Test>> violations = validator.validate(test);
    System.out.println(violations);
```

```
[ConstraintViolationImpl{interpolatedMessage='must not be blank', propertyPath=name,
rootBeanClass=class net.mcmanus.eamonn.autovalueannotations.AutoValue_Test,
messageTemplate='{javax.validation.constraints.NotBlank.message}'}]
```

**Comment by benjaminlefevre** [comment]
@NotBkank targets everything: please see javax.validation 2.0.1 documentation : https://javadoc.io/doc/javax.validation/validation-api/latest/javax/validation/constraints/NotBlank.html

I use the default validator provided by spring boot (I guess hibernate validator) and I got really the constraint violation twice with my example

**Comment by eamonnmcmanus** [comment]
I think this is a bug in the validator framework though, given that it doesn't show up with Hibernate Validator 6.1.1. Perhaps there's a bug that has been fixed, and Spring Boot has an older version without the fix?

The rules for annotation copying are already quite complicated, and I'd be reluctant to make them more so without a more compelling justification.

**Comment by benjaminlefevre** [comment]
I understand. I will do further investigation Monday at work. If it's an issue with an old version of the validator, it will be fixed itself with an upgrade.
Thank you for your time

**Comment by netdpb** [comment]
Closing this issue, as it hasn't had any updates for a while. @benjaminlefevre, please reopen if it's still a problem.
