### ISSUE TITLE
Ensure to process all providers in when generating config files

### ISSUE THREAD

**Issue by bbyk** [google/auto#839]
In `AutoServiceProcessor#generateConfigFiles` the loop over providers can
be left prematurely if for a provider type there is no new services. The
remaining provider types can still have new services though.

This is what I mean: https://github.com/google/auto/pull/837/files#diff-dcad1ce0295bb666afc2cbaa9744949aL193

**Comment by netdpb** [comment]
Hi @bbyk. Can you please sign the CLA so we can look at your #837? Thanks.

**Comment by bbyk** [comment]
Hi @netdpb , it is just a replacement of the `return` statement to `continue` in your own code in https://github.com/google/auto/blob/master/service/processor/src/main/java/com/google/auto/service/processor/AutoServiceProcessor.java#L193 . I think the method returns prematurely since `return` is inside a loop and not all the services are walked yet. Just wanted to point out what I thought was a possible bug. I am ok if the PR is closed.

**Comment by netdpb** [comment]
Thanks!

**Comment by AnEmortalKid** [comment]
Ah, damn beat me to it. I just ran into this and came up with a test that might help catch this, prove it. I made my own processor based off of auto-service and found that having a simple `integration` module helps with things that exist in `CLASS_OUTPUT`. That's hard to unit test since the InMemoryFileManager appends everything to the StandardLocation.CLASS_PATH.

Structure that might help reproduce/catch this:

```
integration/
  src/main/java
    com/fake/
      AppendedService (interface)
      AppendedServiceImpl (implements appended service is tagged with AutoService)
      SomeService (interface) / marked with AutoService
  src/main/resources/
    META-INF/com.fake/AppendedService (this emulates the file existing previously and that impl being tagged with AutoService. Im not entirely sure what part of my setup was holding on to files in target (eager intellij maybe?), but this should cause the generation to find an existing provider with no new impls and hit that `return`
```

For the test, I simply grabbed all the files from `META-INF/services` and counted that there were 2.
