### ISSUE TITLE
AutoValue field names (occur in toString implementation also) should omit "get" prefix in getter names

### ISSUE THREAD

**Issue by leventov** [google/auto#84]
```
@AutoValue
class Foo {
    abstract int getBar();
}
```

I expect `foo.toString` be `"Foo{bar=0}"`, not `"Foo{getBar=0}"`

**Comment by eamonnmcmanus** [comment]
I missed updating this issue at the time, but we eventually made it so that if every abstract method in an `@AutoValue` class looks like `getFoo()` or `boolean isFoo()` then the properties that appear in `toString()` and constructor names will be just plain `foo`. This is exactly what was requested.
