### ISSUE TITLE
Unable to generate AutoValue class referencing class generated by another annotation processor (since 1.5.3)

### ISSUE THREAD

**Issue by devchas** [google/auto#847]
I am writing an annotation processor that generates several classes in a library that also uses AutoValue. Beginning with [1.5.3](https://github.com/google/auto/releases/tag/auto-value-1.5.3), I receive an error during compilation `Did not generate @AutoValue class for com.google.ads.googleads.lib.GoogleAdsClient because it references undefined types`. 

The class using AutoValue both extends and contains references to classes generated by the annotation processor I am writing. Prior to 1.5.3, this worked fine - as I understand it, my annotation processor would generate all necessary classes, and then AutoValue would generate the necessary classes using the generated code. However, since 1.5.3, and in every subsequent version, this does not work producing the error mentioned above.

For reference, [this is where we use AutoValue](https://github.com/googleads/google-ads-java/blob/911a0bd0b049400a2ce92644f035eb8e9848383a/google-ads/src/main/java/com/google/ads/googleads/lib/GoogleAdsClient.java#L69). As you can see, the GoogleAdsClient class extends AbstractGoogleAdsClient. In the public version I've linked to, AbstractGoogleAdsClient is present in the library. However, we will be replacing that class with a version generated by the annotation processor I am writing. There will also be a reference to a generated class in the Builder class, but that is not present in the public library I've linked to.

Any idea what could be causing this or how to fix it?

**Comment by eamonnmcmanus** [comment]
This is a fairly delicate area to get right. Forgive me if I am telling you something you already know, but annotation processing proceeds in "rounds", as follows. The compiler first compiles all the source files that were given to it as input, getting as far as it needs in order to know the structure of each one. Then the first round consists of all these compiled files. Each annotation processor gets to examine each one (or the subset that have annotations that are in its "supported annotations" set), and can output further generated source files. When the first round is over, the compiler compiles those new generated source files, and a second round starts with the compiled result. This continues until no processors output any source files, when there is a final round with no input files where processors can perform any final actions they need.

If you give AutoValue a class `Foo` that references a class `Bar` that doesn't exist, it will assume that that is because `Bar` will be generated by other processors. So it puts `Foo` in a "deferred types" list for that round. On the next round, it will try to process `Foo` again in the hope that `Bar` may have been compiled in the meanwhile, and it will keep doing that until it succeeds, or it reaches the final round without succeeding. The message you mention happens in the latter case.

I've written a test case to check that AutoValue does in fact work when compiling an `@AutoValue abstract class Foo extends Bar` where `Bar` is generated by a later annotation processor. That doesn't mean it _always_ works, but it works for my test case. From the history, it does look as if there were some relevant changes in 1.5.3, but nothing that would obviously affect cases like these. So I think we'd need to know more about what exactly it is that your processor does.

Incidentally, your example code does this:
```
AutoValue_GoogleAdsClient.Builder clientBuilder = new AutoValue_GoogleAdsClient.Builder();
```
and I think it would be more natural to do this:
```
Builder clientBuilder = new AutoValue_GoogleAdsClient.Builder();
```
Generally speaking there should be exactly one reference to `AutoValue_Foo` in each `@AutoValue` class `Foo`.

**Comment by eamonnmcmanus** [comment]
OK, with help from @devchas I was able to isolate the set of circumstances that leads to this. We have something like this:

```
@AutoValue
public abstract class Foo extends GeneratedParent {
  @AutoValue.Builder
  public abstract static class Builder {
    public abstract Builder setGenerated(GeneratedType x);
    public abstract build();
  }
}
```

The class `GeneratedParent` is generated by an annotation processor and includes this method:

```
  public abstract GeneratedType getGenerated();
```

where `GeneratedType` is also generated by an annotation processor (could be the same one or another, doesn't matter). Ordinarily processing would be deferred to the next round as I described earlier, but we only detect the missing parent class when preparing to generate `AutoValue_Foo`. In the example, before getting to that point, AutoValue outputs an error, claiming that `setGenerated(GeneratedType)` doesn't correspond to a getter method. That's because it can't see the `getGenerated` method because it's in the parent class which hasn't been generated yet. (If we did have `GeneratedType getGenerated()` in the `@AutoValue` class then the `ErrorType` it returns would match the `ErrorType` for the parameter to `setGenerated`.) The output error means we never get to the deferral logic, and also I think prevents other annotation processors from running.

I'm not entirely sure what the best fix is. If `AutoValueProcessor` extended [`BasicAnnotationProcessor`](https://javadoc.io/static/com.google.auto/auto-common/0.10/com/google/auto/common/BasicAnnotationProcessor.html) then the missing types would have triggered deferral. However the checking done by `BasicAnnotationProcessor` is too thorough; we know from experience that it would trigger the situation described in its javadoc, where two processors that both extend `BasicAnnotationProcessor` can both defer indefinitely because of circular references.

The simplest change that would fix this particular problem would be to verify that all ancestor types are defined, and defer processing if not. But I don't think that is a complete solution. We could still in principle run into the kind of error described above, for example if the parameter type of a setter was generated and was a type that could be converted into the corresponding getter type (with `ImmutableList.copyOf`, say). I believe the reason that this problem started happening with 1.5.3 is that the logic for handling imports changed then. Before, we manually gathered a set of all referenced types so we could output imports for any that needed them. That meant that we could tell if any of those types were undefined, and I think this happened relatively early on. Starting with 1.5.3, we generate imports only when we're ready to generate all the code, and we never get to that point if AutoValue produced an error earlier.

My current inclination is to scan the abstract methods in the `@AutoValue` and `@AutoValue.Builder` classes and defer processing if any of them have undefined return types or parameter types.
