### ISSUE TITLE
CopyAnnotations used on a type don't exclude for all class properties

### ISSUE THREAD

**Issue by ZacSweers** [google/auto#876]
I would expect this to exclude app `@SuppressWarnings` annotations in the class, but it does not

```java
@CopyAnnotations(excludes = SuppressWarnings.class)
abstract class Example {
  @SuppressWarnings("all")
  abstract String foo();
}
```

**Comment by eamonnmcmanus** [comment]
Possibly it should have been designed that way, but I think it would be an incompatible change now. I'm assuming you meant something like this:

```
@AutoValue
@CopyAnnotations(excludes = SuppressWarnings.class)
@SuppressWarnings("dontCopyMe")
abstract class Example {
  @CopyAnnotations
  @SuppressWarnings("maybeCopyMe")
  @SomeAnnotationThatYouDidWantToCopy
  abstract String foo();
}
```

If somebody already has something like that in their code, then if we changed the semantics we would change the generated code, since it would no longer copy `@SuppressWarnings("maybeCopyMe")`.

**Comment by qingliaowu** [comment]
Good point

**Comment by eamonnmcmanus** [comment]
I think we have to close this because of the incompatible behaviour I described [earlier](https://github.com/google/auto/issues/876#issuecomment-690797505).
