### ISSUE TITLE
Null-Annotations for factory

### ISSUE THREAD

**Issue by frankbenoit** [google/auto#881]
Hi,

is there a way to generate the factories with null-annotations, like the Eclipse JDT @NonNull or @NonNullByDefault?

Franks

**Comment by frankbenoit** [comment]
An implementation might work like this:

AutoFactoryProcessor.getSupportedOptions configures to allow the option "nullAnnotations".
For now the value "JDT" is accepted.

If the javac option `-AnullAnnotations=JDT` is given, then the `@org.eclipse.jdt.annotations.NonNullByDefault` is attached to the factory,

```java
@org.eclipse.jdt.annotation.NonNullByDefault
public class MyClassFactory ...
```

**Comment by eamonnmcmanus** [comment]
Maybe we could do something like [`@AutoValue.CopyAnnotations`](https://www.javadoc.io/doc/com.google.auto.value/auto-value/latest/com/google/auto/value/AutoValue.CopyAnnotations.html). If your `@AutoFactory` class has `@AutoFactory.CopyAnnotations` then any other annotations on it get copied to the implementation. So the source class

```
@AutoFactory
@AutoFactory.CopyAnnotations
@NonNullByDefault
class Whatever {...}
```

would result in the generated class

```
@NonNullByDefault
class WhateverFactory {...}
```

I think that might be better than hardwiring logic about specific annotations.

**Comment by frankbenoit** [comment]
I agree that a more general mechanism would be good.

However, your example for @NonNullByDefault makes the assumption, that the user-class and the factory are always both @NonNullByDefault. But this is not necessarily true. As a user I want to be free, to not have that annotation on my class, but the factory shall have it.

**Comment by frankbenoit** [comment]
I added a proposal implementation for the textual way, see PR #884 

Current limitation:
- no annotation arguments
- FactoryAnnotation is not nested in AutoFactory

**Comment by ronshapiro** [comment]
Related internal bug: b/31342163

**Comment by eamonnmcmanus** [comment]
I'm not sure there's a really good solution here. I did think about a solution similar to #884 but, as @frankbenoit mentions, that doesn't allow annotation arguments, and also requires people to spell out the fully-qualified annotation name in a string constant (since you can't write `@FactoryAnnotation(MyAnnotation.class.getName())`). I guess the second problem could be addressed by making the annotation look like this?

```
public @interface FactoryAnnotation {
  Class<? extends Annotation> value();
}
```

And maybe we could allow for parameters in a slightly clunky way like this:

```
public @interface FactoryAnnotation {
  Class<? extends Annotation> value();
  Argument[] arguments default {};

  @interface Argument {
    String name();
    String value();
  }
}
```

```
@FactoryAnnotation(MyAnnotation.class)
@FactoryAnnotation(
    value = MyAnnotationWithParameters.class, 
    arguments = {
        @Argument(name = "aNumber", value = "1"),
        @Argument(name = "aString", value = "\"hello\""),
    })
@AutoFactory
...
```

Or maybe we just copy some text verbatim into the annotation argument:

```
public @interface FactoryAnnotation {
  Class<? extends Annotation> value();
  String arguments default "";
}
```
```
@FactoryAnnotation(MyAnnotation.class)
@FactoryAnnotation(
    value = MyAnnotationWithParameters.class, 
    arguments = "aNumber = 1, aString = \"hello\"")
@AutoFactory
...
```

A `@CopyAnnotations` solution doesn't have these particular problems because it is based on an actual annotation spelled out with actual annotation syntax. But I agree that this means that people might have to apply an annotation to the `@AutoFactory` class that doesn't really belong there. That's less of a concern with `@AutoValue.CopyAnnotations` because there the annotation is copied from a class to its generated subclass.

The internal bug cited by @ronshapiro seems to be more about copying annotations from the _parameters_ of the `@AutoFactory` constructor to the corresponding parameters of the generated factory. The concern there is that the copying might not always be valid, so it would be safer to do it only if triggered in some way, such as `@CopyAnnotations`.

**Comment by frankbenoit** [comment]
The arguments do not cover nested annotations.
However, this might be yagni anyway.

How about doing it now with this:
```java
public @interface FactoryAnnotation {
  Class<? extends Annotation> value();
}
```

And if needed later on, extend it with the verbatim argument string.

Would you be willing to accept a PR for it?
BTW, if i open the factory project in Eclipse as Maven project, i get compilation errors in the unit test. There seems to be some problem with https://github.com/google/compile-testing/blob/master/src/main/java/com/google/testing/compile/JavaSourcesSubject.java#L595
Here it is referencing Subject without generic args, but the downloaded sources have generic args here. Strange.

**Comment by frankbenoit** [comment]
I created a 3rd proposal, with the class given.

But I have no clue how to create a verbatim text with javapoet. Is it possible to fill the text for all arguments in a single code block?

**Comment by frankbenoit** [comment]
comments?

**Comment by eamonnmcmanus** [comment]
So far we've only seen one motivating use case for this, `@NonNullByDefault`. And, I think there's agreement that it would be nice to be able, optionally, to copy annotations from the parameters of the `@Inject` constructor to the corresponding parameters of the generated factory method. So in the spirit of the-simplest-thing-that-could-possibly-work, I wonder if we can combine those two things, with a `@CopyAnnotations` that allows you to say whether parameter annotations, class annotations, or both should be copied. Yes, an annotation on the generated factory class doesn't necessarily make sense on the `@AutoFactory` class, but if our only example is `@NonNullByDefault`, well then I don't think it's a big deal to have both classes get that behaviour. Are there other annotations that people are likely to want _only_ on the generated class? `@Immutable` maybe?

Yet another possibility would be an option specifying a class from which annotations should be copied. That way you get the full generality of annotation syntax. You might end up creating a dummy class just so that you can put an annotation on it, but that's not a big burden.

```java
@AutoFactory
@CopyAnnotations(
    fromClass = Foo.Annotations.class,
    onParameters = true)
public class Foo {
  @Inject 
  Foo(@CopyMe Bar bar, ...) {...}

  @NonNullByDefault
  private static class Annotations {}
}
```

Then the generated factory class would have the `@NonNullByDefault` annotation copied to it, and its `create` method would have a parameter `@CopyMe Bar bar`.

**Comment by frankbenoit** [comment]
The CopyAnnotation then must implicitly filter out itself and @AutoFactory (more to filter?).
The first minimal implementation would be restricted on class-level and looks like:
```java
@Target({ TYPE })
public @interface CopyAnnotations {
    Class<?> fromClass() default Object.class;
}
```

The feature to copy ctor annotations and ctor-argument annotation to the factory create method, could be implemented later when there is a use case.

**Comment by eamonnmcmanus** [comment]
The new [`@AutoFactory.AnnotationsToApply`](https://github.com/google/auto/blob/d37e51da4d02e77355cba3d2f8d39b4e9a7d8cc8/factory/src/main/java/com/google/auto/factory/AutoFactory.java#L105) feature can be used for this and similar cases.
