### ISSUE TITLE
AutoFactory does not support constructors that throw checked exceptions.

### ISSUE THREAD

**Issue by dbaum** [google/auto#90]
Checked exceptions declared by the constructor should be added to the throw list for the generated create() method.

**Comment by sherter** [comment]
I stumbled across this as well. It might be not a good idea to simply add it to the existing _create()_ method, because then you would need add a try/catch block or rethrow the exception everywhere you want to construct a new object, even if nothing bad can happen . What about a additional _tryCreate() throws Exception_ method?

**Comment by janstrohbeck** [comment]
I had the same problem for one of my projects. The above mentioned pull request worked for me although it adds the exeption types to the create() method.

**Comment by dustinlacewell** [comment]
Ran into this four years later.
