### ISSUE TITLE
Xor as AutoValue.hashCode for Entry-like classes

### ISSUE THREAD

**Issue by leventov** [google/auto#93]
It is `Map.Entry` interface explicit requirement, also should be faster.

**Comment by eamonnmcmanus** [comment]
At this point I don't think we're going to make the change I talked about 5 years ago, of rejecting an `@AutoValue` class if it has an ancestor interface with a `hashCode()` method. It's too likely to break existing code for not a whole lot of benefit. Regarding `Map.Entry` specifically, hopefully people will use `AbstractMap.SimpleImmutableEntry` instead of using `@AutoValue`.
