### ISSUE TITLE
CVE-2020-8908 on for guava < 30.0 

### ISSUE THREAD

**Issue by erilor** [google/auto#959]
It would be nice with a new release of auto-service since the rc7 uses guava 27.0.1 which is affected by the CVE (seems like the version is already bumped on master).

**Comment by Stephan202** [comment]
CVE aside, a new Auto Service release would also help users who have additional annotation classpath dependencies that depend on a more recent Guava release. See e.g. Error Prone: https://github.com/google/error-prone/issues/2138#issuecomment-766314550.

**Comment by cpovirk** [comment]
Fixed for AutoService by [release 1.0](https://github.com/google/auto/releases/tag/auto-service-1.0): https://repo1.maven.org/maven2/com/google/auto/service/auto-service-aggregator/1.0/auto-service-aggregator-1.0.pom

@eamonnmcmanus is releasing all the Auto components, with I believe only AutoFactory yet to come, so that should solve this problem in general. (Of course it will still help if we make frequent releases in the future so that the Dependabot-generated version bumps actually make it into a release.)
