### ISSUE TITLE
Memoize breaks Java 7

### ISSUE THREAD

**Issue by elharo** [google/auto#976]
https://github.com/googleapis/gax-java/issues/1276

Looks like something got compiled with java 8:

When I update to autovalue 1.7 from 1.4 in gax-java I see

    com/google/auto/value/extension/memoized/processor/MemoizedValidator : Unsupported major.minor version 52.0

**Comment by tbroyer** [comment]
https://github.com/google/auto/releases/tag/auto-value-1.5

> This release requires the compiler to be Java 8 or later. It can still generate Java 7 code using -source 7 -target 7, but the compiler itself must be a Java 8 compiler.

**Comment by elharo** [comment]
I see this using OpenJDK 8 to compile for Java 7:

https://github.com/googleapis/gax-java/pull/1267/checks?check_run_id=1768805494

```
Run java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-linux64) (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-linux64) (build 25.282-b08, mixed mode)
```

**Comment by elharo** [comment]
so far I only see this in our bazel build, not the gradle build though that might be nothing more than Gradle generating far less log output by default.

**Comment by eamonnmcmanus** [comment]
I don't think there's an issue here. Please comment if it turns out that there is.

**Comment by elharo** [comment]
I still think there's an issue. I see this warning when compiling with OpenJDK 8.

**Comment by elharo** [comment]
Another broken build that doesn't look like it should be (though perhaps for different reasons): https://github.com/googleapis/gax-java/pull/1278/checks?check_run_id=1769358514

Can we reopen and prioritize this, or should I open a bug internally?

**Comment by eamonnmcmanus** [comment]
"Unsupported major.minor version 52.0" looks like an error because a Java 7 compiler is being used. 52.0 means Java 8 classfiles. Compiling with AutoValue is not supported on Java 7. So I think the issue is why that build is using Java 7, rather than say Java 8 with `-source 7 -target 7`, which _is_ supported.

**Comment by eamonnmcmanus** [comment]
Concerning the [earlier errors](https://github.com/google/auto/issues/976#issuecomment-767615146), it's hard to see what the root cause is given that it looks as if there are several sources of problems. `java.lang.ClassNotFoundException: com.google.api.client.json.jackson2.JacksonFactory` has several Google hits, and I don't think it's related to AutoValue. `-parameters is not supported for target value 1.7. Use 1.8 or later` suggests that something is trying to run `javac -parameters -source 7 -target 7`, which won't work for exactly the reason given in the exception message. I'm not sure if the message `An exception occurred while looking for AutoValue extensions` is related to these problems or something else, but I'd certainly suggesting fixing those first.
